# ruby encoding: utf-8
RivalRegion.create("rivals_id"=>1, "name_ru"=>nil, "name_en"=>"Adygea")
RivalRegion.create("rivals_id"=>2, "name_ru"=>nil, "name_en"=>"Bashkortostan")
RivalRegion.create("rivals_id"=>3, "name_ru"=>nil, "name_en"=>"Buryatia")
RivalRegion.create("rivals_id"=>4, "name_ru"=>nil, "name_en"=>"Altai Republic")
RivalRegion.create("rivals_id"=>5, "name_ru"=>nil, "name_en"=>"Dagestan")
RivalRegion.create("rivals_id"=>6, "name_ru"=>nil, "name_en"=>"Ingushetia")
RivalRegion.create("rivals_id"=>7, "name_ru"=>nil, "name_en"=>"Kabardino-Balkaria")
RivalRegion.create("rivals_id"=>8, "name_ru"=>nil, "name_en"=>"Kalmykia")
RivalRegion.create("rivals_id"=>9, "name_ru"=>nil, "name_en"=>"Karachay-Cherkessia")
RivalRegion.create("rivals_id"=>10, "name_ru"=>nil, "name_en"=>"Republic of Karelia")
RivalRegion.create("rivals_id"=>11, "name_ru"=>nil, "name_en"=>"Komi Republic")
RivalRegion.create("rivals_id"=>12, "name_ru"=>nil, "name_en"=>"Mari El")
RivalRegion.create("rivals_id"=>13, "name_ru"=>nil, "name_en"=>"Mordovia")
RivalRegion.create("rivals_id"=>14, "name_ru"=>nil, "name_en"=>"Sakha Republic")
RivalRegion.create("rivals_id"=>15, "name_ru"=>nil, "name_en"=>"North Ossetia")
RivalRegion.create("rivals_id"=>16, "name_ru"=>nil, "name_en"=>"Tatarstan")
RivalRegion.create("rivals_id"=>17, "name_ru"=>nil, "name_en"=>"Tuva")
RivalRegion.create("rivals_id"=>18, "name_ru"=>nil, "name_en"=>"Udmurtia")
RivalRegion.create("rivals_id"=>19, "name_ru"=>nil, "name_en"=>"Khakassia")
RivalRegion.create("rivals_id"=>20, "name_ru"=>nil, "name_en"=>"Chechnya")
RivalRegion.create("rivals_id"=>21, "name_ru"=>nil, "name_en"=>"Chuvashia")
RivalRegion.create("rivals_id"=>22, "name_ru"=>nil, "name_en"=>"Altai Krai")
RivalRegion.create("rivals_id"=>23, "name_ru"=>nil, "name_en"=>"Krasnodar Krai")
RivalRegion.create("rivals_id"=>24, "name_ru"=>nil, "name_en"=>"Krasnoyarsk Krai")
RivalRegion.create("rivals_id"=>25, "name_ru"=>nil, "name_en"=>"Primorsky Krai")
RivalRegion.create("rivals_id"=>26, "name_ru"=>nil, "name_en"=>"Stavropol Krai")
RivalRegion.create("rivals_id"=>27, "name_ru"=>nil, "name_en"=>"Khabarovsk Krai")
RivalRegion.create("rivals_id"=>28, "name_ru"=>nil, "name_en"=>"Amur Oblast")
RivalRegion.create("rivals_id"=>29, "name_ru"=>nil, "name_en"=>"Arkhangelsk Oblast")
RivalRegion.create("rivals_id"=>30, "name_ru"=>nil, "name_en"=>"Astrakhan Oblast")
RivalRegion.create("rivals_id"=>31, "name_ru"=>nil, "name_en"=>"Belgorod Oblast")
RivalRegion.create("rivals_id"=>32, "name_ru"=>nil, "name_en"=>"Bryansk Oblast")
RivalRegion.create("rivals_id"=>33, "name_ru"=>nil, "name_en"=>"Vladimir Oblast")
RivalRegion.create("rivals_id"=>34, "name_ru"=>nil, "name_en"=>"Volgograd Oblast")
RivalRegion.create("rivals_id"=>35, "name_ru"=>nil, "name_en"=>"Vologda Oblast")
RivalRegion.create("rivals_id"=>36, "name_ru"=>nil, "name_en"=>"Voronezh Oblast")
RivalRegion.create("rivals_id"=>37, "name_ru"=>nil, "name_en"=>"Ivanovo Oblast")
RivalRegion.create("rivals_id"=>38, "name_ru"=>nil, "name_en"=>"Irkutsk Oblast")
RivalRegion.create("rivals_id"=>39, "name_ru"=>nil, "name_en"=>"Kaliningrad Oblast")
RivalRegion.create("rivals_id"=>40, "name_ru"=>nil, "name_en"=>"Kaluga Oblast")
RivalRegion.create("rivals_id"=>41, "name_ru"=>nil, "name_en"=>"Kamchatka Krai")
RivalRegion.create("rivals_id"=>42, "name_ru"=>nil, "name_en"=>"Kemerovo Oblast")
RivalRegion.create("rivals_id"=>43, "name_ru"=>nil, "name_en"=>"Kirov Oblast")
RivalRegion.create("rivals_id"=>44, "name_ru"=>nil, "name_en"=>"Kostroma Oblast")
RivalRegion.create("rivals_id"=>45, "name_ru"=>nil, "name_en"=>"Kurgan Oblast")
RivalRegion.create("rivals_id"=>46, "name_ru"=>nil, "name_en"=>"Kursk Oblast")
RivalRegion.create("rivals_id"=>47, "name_ru"=>nil, "name_en"=>"Leningrad Oblast")
RivalRegion.create("rivals_id"=>48, "name_ru"=>nil, "name_en"=>"Lipetsk Oblast")
RivalRegion.create("rivals_id"=>49, "name_ru"=>nil, "name_en"=>"Magadan Oblast")
RivalRegion.create("rivals_id"=>50, "name_ru"=>nil, "name_en"=>"Moscow Oblast")
RivalRegion.create("rivals_id"=>51, "name_ru"=>nil, "name_en"=>"Murmansk Oblast")
RivalRegion.create("rivals_id"=>52, "name_ru"=>nil, "name_en"=>"Nizhny Novgorod Oblast")
RivalRegion.create("rivals_id"=>53, "name_ru"=>nil, "name_en"=>"Novgorod Oblast")
RivalRegion.create("rivals_id"=>54, "name_ru"=>nil, "name_en"=>"Novosibirsk Oblast")
RivalRegion.create("rivals_id"=>55, "name_ru"=>nil, "name_en"=>"Omsk Oblast")
RivalRegion.create("rivals_id"=>56, "name_ru"=>nil, "name_en"=>"Orenburg Oblast")
RivalRegion.create("rivals_id"=>57, "name_ru"=>nil, "name_en"=>"Oryol Oblast")
RivalRegion.create("rivals_id"=>58, "name_ru"=>nil, "name_en"=>"Penza Oblast")
RivalRegion.create("rivals_id"=>59, "name_ru"=>nil, "name_en"=>"Perm Krai")
RivalRegion.create("rivals_id"=>60, "name_ru"=>nil, "name_en"=>"Pskov Oblast")
RivalRegion.create("rivals_id"=>61, "name_ru"=>nil, "name_en"=>"Rostov Oblast")
RivalRegion.create("rivals_id"=>62, "name_ru"=>nil, "name_en"=>"Ryazan Oblast")
RivalRegion.create("rivals_id"=>63, "name_ru"=>nil, "name_en"=>"Samara Oblast")
RivalRegion.create("rivals_id"=>64, "name_ru"=>nil, "name_en"=>"Saratov Oblast")
RivalRegion.create("rivals_id"=>65, "name_ru"=>nil, "name_en"=>"Sakhalin Oblast")
RivalRegion.create("rivals_id"=>66, "name_ru"=>nil, "name_en"=>"Sverdlovsk Oblast")
RivalRegion.create("rivals_id"=>67, "name_ru"=>nil, "name_en"=>"Smolensk Oblast")
RivalRegion.create("rivals_id"=>68, "name_ru"=>nil, "name_en"=>"Tambov Oblast")
RivalRegion.create("rivals_id"=>69, "name_ru"=>nil, "name_en"=>"Tver Oblast")
RivalRegion.create("rivals_id"=>70, "name_ru"=>nil, "name_en"=>"Tomsk Oblast")
RivalRegion.create("rivals_id"=>71, "name_ru"=>nil, "name_en"=>"Tula Oblast")
RivalRegion.create("rivals_id"=>72, "name_ru"=>nil, "name_en"=>"Tyumen Oblast")
RivalRegion.create("rivals_id"=>73, "name_ru"=>nil, "name_en"=>"Ulyanovsk Oblast")
RivalRegion.create("rivals_id"=>74, "name_ru"=>nil, "name_en"=>"Chelyabinsk Oblast")
RivalRegion.create("rivals_id"=>75, "name_ru"=>nil, "name_en"=>"Zabaykalsky Krai")
RivalRegion.create("rivals_id"=>76, "name_ru"=>nil, "name_en"=>"Yaroslavl Oblast")
RivalRegion.create("rivals_id"=>77, "name_ru"=>nil, "name_en"=>"Moscow")
RivalRegion.create("rivals_id"=>78, "name_ru"=>nil, "name_en"=>"Saint Petersburg")
RivalRegion.create("rivals_id"=>79, "name_ru"=>nil, "name_en"=>"Jewish AO")
RivalRegion.create("rivals_id"=>80, "name_ru"=>nil, "name_en"=>"Novosibirsk")
RivalRegion.create("rivals_id"=>81, "name_ru"=>nil, "name_en"=>"Yekaterinburg")
RivalRegion.create("rivals_id"=>82, "name_ru"=>nil, "name_en"=>"Nizhny Novgorod")
RivalRegion.create("rivals_id"=>83, "name_ru"=>nil, "name_en"=>"Nenets AO")
RivalRegion.create("rivals_id"=>84, "name_ru"=>nil, "name_en"=>"Kazan")
RivalRegion.create("rivals_id"=>85, "name_ru"=>nil, "name_en"=>"Samara")
RivalRegion.create("rivals_id"=>86, "name_ru"=>nil, "name_en"=>"Khanty-Mansi AO")
RivalRegion.create("rivals_id"=>87, "name_ru"=>nil, "name_en"=>"Chukotka AO")
RivalRegion.create("rivals_id"=>89, "name_ru"=>nil, "name_en"=>"Yamalo-Nenets AO")
RivalRegion.create("rivals_id"=>90, "name_ru"=>nil, "name_en"=>"Grozny")
RivalRegion.create("rivals_id"=>91, "name_ru"=>nil, "name_en"=>"Makhachkala")
RivalRegion.create("rivals_id"=>101, "name_ru"=>nil, "name_en"=>"Zakarpattia Oblast")
RivalRegion.create("rivals_id"=>102, "name_ru"=>nil, "name_en"=>"Kirovohrad Oblast")
RivalRegion.create("rivals_id"=>103, "name_ru"=>nil, "name_en"=>"Mykolaiv Oblast")
RivalRegion.create("rivals_id"=>104, "name_ru"=>nil, "name_en"=>"Kharkiv Oblast")
RivalRegion.create("rivals_id"=>105, "name_ru"=>nil, "name_en"=>"Luhansk Oblast")
RivalRegion.create("rivals_id"=>106, "name_ru"=>nil, "name_en"=>"Donetsk Oblast")
RivalRegion.create("rivals_id"=>107, "name_ru"=>nil, "name_en"=>"Dnipropetrovsk Oblast")
RivalRegion.create("rivals_id"=>108, "name_ru"=>nil, "name_en"=>"Zaporizhia Oblast")
RivalRegion.create("rivals_id"=>109, "name_ru"=>nil, "name_en"=>"Kherson Oblast")
RivalRegion.create("rivals_id"=>110, "name_ru"=>nil, "name_en"=>"Crimea Republic")
RivalRegion.create("rivals_id"=>111, "name_ru"=>nil, "name_en"=>"Odessa Oblast")
RivalRegion.create("rivals_id"=>112, "name_ru"=>nil, "name_en"=>"Vinnytsia Oblast")
RivalRegion.create("rivals_id"=>113, "name_ru"=>nil, "name_en"=>"Khmelnytskyi Oblast")
RivalRegion.create("rivals_id"=>114, "name_ru"=>nil, "name_en"=>"Chernivtsi Oblast")
RivalRegion.create("rivals_id"=>115, "name_ru"=>nil, "name_en"=>"Ivano-Frankivsk Oblast")
RivalRegion.create("rivals_id"=>116, "name_ru"=>nil, "name_en"=>"Ternopil Oblast")
RivalRegion.create("rivals_id"=>117, "name_ru"=>nil, "name_en"=>"Lviv Oblast")
RivalRegion.create("rivals_id"=>118, "name_ru"=>nil, "name_en"=>"Volyn Oblast")
RivalRegion.create("rivals_id"=>119, "name_ru"=>nil, "name_en"=>"Rivne Oblast")
RivalRegion.create("rivals_id"=>120, "name_ru"=>nil, "name_en"=>"Zhytomyr Oblast")
RivalRegion.create("rivals_id"=>121, "name_ru"=>nil, "name_en"=>"Kiev Oblast")
RivalRegion.create("rivals_id"=>122, "name_ru"=>nil, "name_en"=>"Cherkasy Oblast")
RivalRegion.create("rivals_id"=>123, "name_ru"=>nil, "name_en"=>"Poltava Oblast")
RivalRegion.create("rivals_id"=>124, "name_ru"=>nil, "name_en"=>"Sumy Oblast")
RivalRegion.create("rivals_id"=>125, "name_ru"=>nil, "name_en"=>"Chernihiv Oblast")
RivalRegion.create("rivals_id"=>126, "name_ru"=>nil, "name_en"=>"Kiev")
RivalRegion.create("rivals_id"=>127, "name_ru"=>nil, "name_en"=>"Sevastopol")
RivalRegion.create("rivals_id"=>128, "name_ru"=>nil, "name_en"=>"Kharkiv")
RivalRegion.create("rivals_id"=>129, "name_ru"=>nil, "name_en"=>"Odessa")
RivalRegion.create("rivals_id"=>130, "name_ru"=>nil, "name_en"=>"Dniepr")
RivalRegion.create("rivals_id"=>131, "name_ru"=>nil, "name_en"=>"Lviv")
RivalRegion.create("rivals_id"=>132, "name_ru"=>nil, "name_en"=>"Zaporizhia")
RivalRegion.create("rivals_id"=>133, "name_ru"=>nil, "name_en"=>"Donetsk")
RivalRegion.create("rivals_id"=>201, "name_ru"=>nil, "name_en"=>"Brest Oblast")
RivalRegion.create("rivals_id"=>202, "name_ru"=>nil, "name_en"=>"Vitebsk Oblast")
RivalRegion.create("rivals_id"=>203, "name_ru"=>nil, "name_en"=>"Gomel Oblast")
RivalRegion.create("rivals_id"=>204, "name_ru"=>nil, "name_en"=>"Grodno Oblast")
RivalRegion.create("rivals_id"=>205, "name_ru"=>nil, "name_en"=>"Minsk Oblast")
RivalRegion.create("rivals_id"=>206, "name_ru"=>nil, "name_en"=>"Mogilyov Oblast")
RivalRegion.create("rivals_id"=>207, "name_ru"=>nil, "name_en"=>"Minsk")
RivalRegion.create("rivals_id"=>208, "name_ru"=>nil, "name_en"=>"Gomel")
RivalRegion.create("rivals_id"=>209, "name_ru"=>nil, "name_en"=>"Vitebsk")
RivalRegion.create("rivals_id"=>301, "name_ru"=>nil, "name_en"=>"Akmola Region")
RivalRegion.create("rivals_id"=>302, "name_ru"=>nil, "name_en"=>"East Kazakhstan Region")
RivalRegion.create("rivals_id"=>303, "name_ru"=>nil, "name_en"=>"Jambyl Region")
RivalRegion.create("rivals_id"=>304, "name_ru"=>nil, "name_en"=>"Aktobe Region")
RivalRegion.create("rivals_id"=>305, "name_ru"=>nil, "name_en"=>"Karaganda Region")
RivalRegion.create("rivals_id"=>306, "name_ru"=>nil, "name_en"=>"Astana")
RivalRegion.create("rivals_id"=>307, "name_ru"=>nil, "name_en"=>"Almaty")
RivalRegion.create("rivals_id"=>308, "name_ru"=>nil, "name_en"=>"Almaty Region")
RivalRegion.create("rivals_id"=>309, "name_ru"=>nil, "name_en"=>"South Kazakhstan Region")
RivalRegion.create("rivals_id"=>310, "name_ru"=>nil, "name_en"=>"Kyzylorda Region")
RivalRegion.create("rivals_id"=>311, "name_ru"=>nil, "name_en"=>"Mangystau Region")
RivalRegion.create("rivals_id"=>312, "name_ru"=>nil, "name_en"=>"Atyrau Region")
RivalRegion.create("rivals_id"=>313, "name_ru"=>nil, "name_en"=>"West Kazakhstan Region")
RivalRegion.create("rivals_id"=>314, "name_ru"=>nil, "name_en"=>"North-Kazakhstan region")
RivalRegion.create("rivals_id"=>315, "name_ru"=>nil, "name_en"=>"Pavlodar Region")
RivalRegion.create("rivals_id"=>316, "name_ru"=>nil, "name_en"=>"Kostanay Region")
RivalRegion.create("rivals_id"=>401, "name_ru"=>nil, "name_en"=>"Dainava")
RivalRegion.create("rivals_id"=>402, "name_ru"=>nil, "name_en"=>"Suvalkija")
RivalRegion.create("rivals_id"=>403, "name_ru"=>nil, "name_en"=>"Lithuania Minor")
RivalRegion.create("rivals_id"=>404, "name_ru"=>nil, "name_en"=>"Samogitia")
RivalRegion.create("rivals_id"=>405, "name_ru"=>nil, "name_en"=>"Aukštaitija")
RivalRegion.create("rivals_id"=>406, "name_ru"=>nil, "name_en"=>"Vilnius")
RivalRegion.create("rivals_id"=>501, "name_ru"=>nil, "name_en"=>"Riga")
RivalRegion.create("rivals_id"=>502, "name_ru"=>nil, "name_en"=>"Vidzeme")
RivalRegion.create("rivals_id"=>503, "name_ru"=>nil, "name_en"=>"Latgale")
RivalRegion.create("rivals_id"=>504, "name_ru"=>nil, "name_en"=>"Zemgale")
RivalRegion.create("rivals_id"=>505, "name_ru"=>nil, "name_en"=>"Courland")
RivalRegion.create("rivals_id"=>601, "name_ru"=>nil, "name_en"=>"Tallinn")
RivalRegion.create("rivals_id"=>602, "name_ru"=>nil, "name_en"=>"Rakvere")
RivalRegion.create("rivals_id"=>603, "name_ru"=>nil, "name_en"=>"Jõhvi")
RivalRegion.create("rivals_id"=>604, "name_ru"=>nil, "name_en"=>"Tartu")
RivalRegion.create("rivals_id"=>605, "name_ru"=>nil, "name_en"=>"Pärnu")
RivalRegion.create("rivals_id"=>701, "name_ru"=>nil, "name_en"=>"Masovia")
RivalRegion.create("rivals_id"=>702, "name_ru"=>nil, "name_en"=>"Greater Poland")
RivalRegion.create("rivals_id"=>703, "name_ru"=>nil, "name_en"=>"Podlaskie")
RivalRegion.create("rivals_id"=>704, "name_ru"=>nil, "name_en"=>"Pomerania")
RivalRegion.create("rivals_id"=>705, "name_ru"=>nil, "name_en"=>"Lesser Poland")
RivalRegion.create("rivals_id"=>706, "name_ru"=>nil, "name_en"=>"Lower Silesia")
RivalRegion.create("rivals_id"=>707, "name_ru"=>nil, "name_en"=>"Kuyavia-Pomerania")
RivalRegion.create("rivals_id"=>708, "name_ru"=>nil, "name_en"=>"Lublin")
RivalRegion.create("rivals_id"=>709, "name_ru"=>nil, "name_en"=>"Lubusz")
RivalRegion.create("rivals_id"=>710, "name_ru"=>nil, "name_en"=>"Lodz")
RivalRegion.create("rivals_id"=>711, "name_ru"=>nil, "name_en"=>"Opole")
RivalRegion.create("rivals_id"=>712, "name_ru"=>nil, "name_en"=>"Subcarpathia")
RivalRegion.create("rivals_id"=>713, "name_ru"=>nil, "name_en"=>"Holy Cross Province")
RivalRegion.create("rivals_id"=>714, "name_ru"=>nil, "name_en"=>"Silesia")
RivalRegion.create("rivals_id"=>715, "name_ru"=>nil, "name_en"=>"Warmia-Masuria")
RivalRegion.create("rivals_id"=>716, "name_ru"=>nil, "name_en"=>"West Pomerania")
RivalRegion.create("rivals_id"=>717, "name_ru"=>nil, "name_en"=>"Warsaw")
RivalRegion.create("rivals_id"=>718, "name_ru"=>nil, "name_en"=>"Kraków")
RivalRegion.create("rivals_id"=>719, "name_ru"=>nil, "name_en"=>"Lodz City")
RivalRegion.create("rivals_id"=>801, "name_ru"=>nil, "name_en"=>"Azerbaijan")
RivalRegion.create("rivals_id"=>802, "name_ru"=>nil, "name_en"=>"Georgia")
RivalRegion.create("rivals_id"=>803, "name_ru"=>nil, "name_en"=>"Yerevan")
RivalRegion.create("rivals_id"=>804, "name_ru"=>nil, "name_en"=>"Abkhazia")
RivalRegion.create("rivals_id"=>805, "name_ru"=>nil, "name_en"=>"South Ossetia")
RivalRegion.create("rivals_id"=>806, "name_ru"=>nil, "name_en"=>"Nagorno-Karabakh")
RivalRegion.create("rivals_id"=>807, "name_ru"=>nil, "name_en"=>"Nakhchivan Autonomous Republic")
RivalRegion.create("rivals_id"=>808, "name_ru"=>nil, "name_en"=>"Adjara")
RivalRegion.create("rivals_id"=>809, "name_ru"=>nil, "name_en"=>"Baku")
RivalRegion.create("rivals_id"=>810, "name_ru"=>nil, "name_en"=>"Tbilisi")
RivalRegion.create("rivals_id"=>811, "name_ru"=>nil, "name_en"=>"Ganja")
RivalRegion.create("rivals_id"=>901, "name_ru"=>nil, "name_en"=>"Baden-Württemberg")
RivalRegion.create("rivals_id"=>902, "name_ru"=>nil, "name_en"=>"Bavaria")
RivalRegion.create("rivals_id"=>903, "name_ru"=>nil, "name_en"=>"Brandenburg")
RivalRegion.create("rivals_id"=>904, "name_ru"=>nil, "name_en"=>"Hesse")
RivalRegion.create("rivals_id"=>905, "name_ru"=>nil, "name_en"=>"Mecklenburg-Vorpommern")
RivalRegion.create("rivals_id"=>906, "name_ru"=>nil, "name_en"=>"Lower Saxony")
RivalRegion.create("rivals_id"=>907, "name_ru"=>nil, "name_en"=>"North Rhine-Westphalia")
RivalRegion.create("rivals_id"=>908, "name_ru"=>nil, "name_en"=>"Rhineland-Palatinate")
RivalRegion.create("rivals_id"=>909, "name_ru"=>nil, "name_en"=>"Saarland")
RivalRegion.create("rivals_id"=>910, "name_ru"=>nil, "name_en"=>"Saxony")
RivalRegion.create("rivals_id"=>911, "name_ru"=>nil, "name_en"=>"Saxony-Anhalt")
RivalRegion.create("rivals_id"=>912, "name_ru"=>nil, "name_en"=>"Schleswig-Holstein")
RivalRegion.create("rivals_id"=>913, "name_ru"=>nil, "name_en"=>"Thuringia")
RivalRegion.create("rivals_id"=>914, "name_ru"=>nil, "name_en"=>"Berlin")
RivalRegion.create("rivals_id"=>915, "name_ru"=>nil, "name_en"=>"Munich")
RivalRegion.create("rivals_id"=>916, "name_ru"=>nil, "name_en"=>"Hamburg")
RivalRegion.create("rivals_id"=>917, "name_ru"=>nil, "name_en"=>"Cologne")
RivalRegion.create("rivals_id"=>1001, "name_ru"=>nil, "name_en"=>"Burgenland")
RivalRegion.create("rivals_id"=>1002, "name_ru"=>nil, "name_en"=>"Carinthia")
RivalRegion.create("rivals_id"=>1003, "name_ru"=>nil, "name_en"=>"Lower Austria")
RivalRegion.create("rivals_id"=>1004, "name_ru"=>nil, "name_en"=>"Upper Austria")
RivalRegion.create("rivals_id"=>1005, "name_ru"=>nil, "name_en"=>"Salzburg")
RivalRegion.create("rivals_id"=>1006, "name_ru"=>nil, "name_en"=>"Styria")
RivalRegion.create("rivals_id"=>1007, "name_ru"=>nil, "name_en"=>"Tyrol")
RivalRegion.create("rivals_id"=>1008, "name_ru"=>nil, "name_en"=>"Vorarlberg")
RivalRegion.create("rivals_id"=>1009, "name_ru"=>nil, "name_en"=>"Vienna")
RivalRegion.create("rivals_id"=>1101, "name_ru"=>nil, "name_en"=>"Central Moravia")
RivalRegion.create("rivals_id"=>1102, "name_ru"=>nil, "name_en"=>"Southwest Czech Republic")
RivalRegion.create("rivals_id"=>1103, "name_ru"=>nil, "name_en"=>"Northwest Czech Republic")
RivalRegion.create("rivals_id"=>1104, "name_ru"=>nil, "name_en"=>"Southeast Czech Republic")
RivalRegion.create("rivals_id"=>1105, "name_ru"=>nil, "name_en"=>"Northeast Czech Republic")
RivalRegion.create("rivals_id"=>1106, "name_ru"=>nil, "name_en"=>"Central Bohemian")
RivalRegion.create("rivals_id"=>1107, "name_ru"=>nil, "name_en"=>"Moravian-Silesian")
RivalRegion.create("rivals_id"=>1108, "name_ru"=>nil, "name_en"=>"Prague")
RivalRegion.create("rivals_id"=>1109, "name_ru"=>nil, "name_en"=>"Brno")
RivalRegion.create("rivals_id"=>1201, "name_ru"=>nil, "name_en"=>"Bratislava")
RivalRegion.create("rivals_id"=>1202, "name_ru"=>nil, "name_en"=>"Trnava")
RivalRegion.create("rivals_id"=>1203, "name_ru"=>nil, "name_en"=>"Trenčín")
RivalRegion.create("rivals_id"=>1204, "name_ru"=>nil, "name_en"=>"Nitra")
RivalRegion.create("rivals_id"=>1205, "name_ru"=>nil, "name_en"=>"Žilina")
RivalRegion.create("rivals_id"=>1206, "name_ru"=>nil, "name_en"=>"Banská Bystrica")
RivalRegion.create("rivals_id"=>1207, "name_ru"=>nil, "name_en"=>"Prešov")
RivalRegion.create("rivals_id"=>1208, "name_ru"=>nil, "name_en"=>"Košice")
RivalRegion.create("rivals_id"=>1301, "name_ru"=>nil, "name_en"=>"Northwest Romania")
RivalRegion.create("rivals_id"=>1302, "name_ru"=>nil, "name_en"=>"Central Romania")
RivalRegion.create("rivals_id"=>1303, "name_ru"=>nil, "name_en"=>"Northeast Romania")
RivalRegion.create("rivals_id"=>1304, "name_ru"=>nil, "name_en"=>"Southeast Romania")
RivalRegion.create("rivals_id"=>1305, "name_ru"=>nil, "name_en"=>"South Romania")
RivalRegion.create("rivals_id"=>1306, "name_ru"=>nil, "name_en"=>"Southwest Romania")
RivalRegion.create("rivals_id"=>1307, "name_ru"=>nil, "name_en"=>"West Romania")
RivalRegion.create("rivals_id"=>1308, "name_ru"=>nil, "name_en"=>"Bucharest")
RivalRegion.create("rivals_id"=>1309, "name_ru"=>nil, "name_en"=>"Timisoara")
RivalRegion.create("rivals_id"=>1401, "name_ru"=>nil, "name_en"=>"Transnistria")
RivalRegion.create("rivals_id"=>1501, "name_ru"=>nil, "name_en"=>"South Moldova")
RivalRegion.create("rivals_id"=>1502, "name_ru"=>nil, "name_en"=>"Central Moldova")
RivalRegion.create("rivals_id"=>1503, "name_ru"=>nil, "name_en"=>"North Moldova")
RivalRegion.create("rivals_id"=>1504, "name_ru"=>nil, "name_en"=>"Chisinau")
RivalRegion.create("rivals_id"=>1601, "name_ru"=>nil, "name_en"=>"Central Hungary")
RivalRegion.create("rivals_id"=>1602, "name_ru"=>nil, "name_en"=>"Transdanubia")
RivalRegion.create("rivals_id"=>1603, "name_ru"=>nil, "name_en"=>"Great Plain and North")
RivalRegion.create("rivals_id"=>1604, "name_ru"=>nil, "name_en"=>"Budapest")
RivalRegion.create("rivals_id"=>1701, "name_ru"=>nil, "name_en"=>"Izmir Subregion")
RivalRegion.create("rivals_id"=>1702, "name_ru"=>nil, "name_en"=>"Zonguldak")
RivalRegion.create("rivals_id"=>1703, "name_ru"=>nil, "name_en"=>"Kırıkkale")
RivalRegion.create("rivals_id"=>1704, "name_ru"=>nil, "name_en"=>"Erzurum")
RivalRegion.create("rivals_id"=>1705, "name_ru"=>nil, "name_en"=>"Istanbul Subregion")
RivalRegion.create("rivals_id"=>1706, "name_ru"=>nil, "name_en"=>"Antalya")
RivalRegion.create("rivals_id"=>1707, "name_ru"=>nil, "name_en"=>"Gaziantep")
RivalRegion.create("rivals_id"=>1708, "name_ru"=>nil, "name_en"=>"Istanbul")
RivalRegion.create("rivals_id"=>1709, "name_ru"=>nil, "name_en"=>"Ankara")
RivalRegion.create("rivals_id"=>1710, "name_ru"=>nil, "name_en"=>"Tekirdağ")
RivalRegion.create("rivals_id"=>1711, "name_ru"=>nil, "name_en"=>"Balıkesir")
RivalRegion.create("rivals_id"=>1712, "name_ru"=>nil, "name_en"=>"Aydın")
RivalRegion.create("rivals_id"=>1713, "name_ru"=>nil, "name_en"=>"Manisa")
RivalRegion.create("rivals_id"=>1714, "name_ru"=>nil, "name_en"=>"Bursa")
RivalRegion.create("rivals_id"=>1715, "name_ru"=>nil, "name_en"=>"Kocaeli")
RivalRegion.create("rivals_id"=>1716, "name_ru"=>nil, "name_en"=>"Ankara Subregion")
RivalRegion.create("rivals_id"=>1717, "name_ru"=>nil, "name_en"=>"Konya")
RivalRegion.create("rivals_id"=>1718, "name_ru"=>nil, "name_en"=>"Adana")
RivalRegion.create("rivals_id"=>1719, "name_ru"=>nil, "name_en"=>"Hatay")
RivalRegion.create("rivals_id"=>1720, "name_ru"=>nil, "name_en"=>"Kayseri")
RivalRegion.create("rivals_id"=>1721, "name_ru"=>nil, "name_en"=>"Kastamonu")
RivalRegion.create("rivals_id"=>1722, "name_ru"=>nil, "name_en"=>"Samsun")
RivalRegion.create("rivals_id"=>1723, "name_ru"=>nil, "name_en"=>"Trabzon")
RivalRegion.create("rivals_id"=>1724, "name_ru"=>nil, "name_en"=>"Ağrı")
RivalRegion.create("rivals_id"=>1725, "name_ru"=>nil, "name_en"=>"Malatya")
RivalRegion.create("rivals_id"=>1726, "name_ru"=>nil, "name_en"=>"Van")
RivalRegion.create("rivals_id"=>1727, "name_ru"=>nil, "name_en"=>"Şanlıurfa")
RivalRegion.create("rivals_id"=>1728, "name_ru"=>nil, "name_en"=>"Mardin")
RivalRegion.create("rivals_id"=>1729, "name_ru"=>nil, "name_en"=>"Izmir")
RivalRegion.create("rivals_id"=>1730, "name_ru"=>nil, "name_en"=>"Bursa City")
RivalRegion.create("rivals_id"=>1731, "name_ru"=>nil, "name_en"=>"Adana City")
RivalRegion.create("rivals_id"=>1801, "name_ru"=>nil, "name_en"=>"Åland Islands")
RivalRegion.create("rivals_id"=>1802, "name_ru"=>nil, "name_en"=>"East Finland")
RivalRegion.create("rivals_id"=>1803, "name_ru"=>nil, "name_en"=>"South Finland")
RivalRegion.create("rivals_id"=>1804, "name_ru"=>nil, "name_en"=>"West Finland")
RivalRegion.create("rivals_id"=>1805, "name_ru"=>nil, "name_en"=>"North Finland")
RivalRegion.create("rivals_id"=>1806, "name_ru"=>nil, "name_en"=>"Helsinki")
RivalRegion.create("rivals_id"=>1901, "name_ru"=>nil, "name_en"=>"East Middle Sweden")
RivalRegion.create("rivals_id"=>1902, "name_ru"=>nil, "name_en"=>"South Sweden")
RivalRegion.create("rivals_id"=>1903, "name_ru"=>nil, "name_en"=>"North Middle Sweden")
RivalRegion.create("rivals_id"=>1904, "name_ru"=>nil, "name_en"=>"Middle Norrland")
RivalRegion.create("rivals_id"=>1905, "name_ru"=>nil, "name_en"=>"Upper Norrland")
RivalRegion.create("rivals_id"=>1906, "name_ru"=>nil, "name_en"=>"Småland and the islands")
RivalRegion.create("rivals_id"=>1907, "name_ru"=>nil, "name_en"=>"West Sweden")
RivalRegion.create("rivals_id"=>1908, "name_ru"=>nil, "name_en"=>"Stockholm")
RivalRegion.create("rivals_id"=>2001, "name_ru"=>nil, "name_en"=>"Central Israel")
RivalRegion.create("rivals_id"=>2002, "name_ru"=>nil, "name_en"=>"Northern Israel")
RivalRegion.create("rivals_id"=>2003, "name_ru"=>nil, "name_en"=>"Haifa")
RivalRegion.create("rivals_id"=>2004, "name_ru"=>nil, "name_en"=>"Jerusalem")
RivalRegion.create("rivals_id"=>2005, "name_ru"=>nil, "name_en"=>"Southern Israel")
RivalRegion.create("rivals_id"=>2006, "name_ru"=>nil, "name_en"=>"Gaza Strip")
RivalRegion.create("rivals_id"=>2007, "name_ru"=>nil, "name_en"=>"West Bank")
RivalRegion.create("rivals_id"=>2008, "name_ru"=>nil, "name_en"=>"Golan Heights")
RivalRegion.create("rivals_id"=>2009, "name_ru"=>nil, "name_en"=>"Lebanon")
RivalRegion.create("rivals_id"=>2010, "name_ru"=>nil, "name_en"=>"Southern Syria")
RivalRegion.create("rivals_id"=>2011, "name_ru"=>nil, "name_en"=>"Northern Syria")
RivalRegion.create("rivals_id"=>2012, "name_ru"=>nil, "name_en"=>"Northern Cyprus")
RivalRegion.create("rivals_id"=>2013, "name_ru"=>nil, "name_en"=>"Cyprus")
RivalRegion.create("rivals_id"=>2101, "name_ru"=>nil, "name_en"=>"Northern Norway")
RivalRegion.create("rivals_id"=>2102, "name_ru"=>nil, "name_en"=>"Trøndelag")
RivalRegion.create("rivals_id"=>2103, "name_ru"=>nil, "name_en"=>"Western Norway")
RivalRegion.create("rivals_id"=>2104, "name_ru"=>nil, "name_en"=>"Southern Norway")
RivalRegion.create("rivals_id"=>2105, "name_ru"=>nil, "name_en"=>"Eastern Norway")
RivalRegion.create("rivals_id"=>2106, "name_ru"=>nil, "name_en"=>"Svalbard")
RivalRegion.create("rivals_id"=>2107, "name_ru"=>nil, "name_en"=>"Oslo")
RivalRegion.create("rivals_id"=>2201, "name_ru"=>nil, "name_en"=>"North Denmark")
RivalRegion.create("rivals_id"=>2202, "name_ru"=>nil, "name_en"=>"Central Denmark")
RivalRegion.create("rivals_id"=>2203, "name_ru"=>nil, "name_en"=>"Southern Denmark")
RivalRegion.create("rivals_id"=>2204, "name_ru"=>nil, "name_en"=>"Zealand")
RivalRegion.create("rivals_id"=>2205, "name_ru"=>nil, "name_en"=>"Capital Region of Denmark")
RivalRegion.create("rivals_id"=>2206, "name_ru"=>nil, "name_en"=>"Greenland")
RivalRegion.create("rivals_id"=>2207, "name_ru"=>nil, "name_en"=>"Faroe Islands")
RivalRegion.create("rivals_id"=>2208, "name_ru"=>nil, "name_en"=>"Copenhagen")
RivalRegion.create("rivals_id"=>2301, "name_ru"=>nil, "name_en"=>"Iceland")
RivalRegion.create("rivals_id"=>2401, "name_ru"=>nil, "name_en"=>"North Central Bulgaria")
RivalRegion.create("rivals_id"=>2402, "name_ru"=>nil, "name_en"=>"North West Bulgaria")
RivalRegion.create("rivals_id"=>2403, "name_ru"=>nil, "name_en"=>"North East Bulgaria")
RivalRegion.create("rivals_id"=>2404, "name_ru"=>nil, "name_en"=>"South East Bulgaria")
RivalRegion.create("rivals_id"=>2405, "name_ru"=>nil, "name_en"=>"South West Bulgaria")
RivalRegion.create("rivals_id"=>2406, "name_ru"=>nil, "name_en"=>"South Central Bulgaria")
RivalRegion.create("rivals_id"=>2407, "name_ru"=>nil, "name_en"=>"Sofia")
RivalRegion.create("rivals_id"=>2501, "name_ru"=>nil, "name_en"=>"Northern Greece")
RivalRegion.create("rivals_id"=>2502, "name_ru"=>nil, "name_en"=>"Central Greece")
RivalRegion.create("rivals_id"=>2503, "name_ru"=>nil, "name_en"=>"Attiki")
RivalRegion.create("rivals_id"=>2504, "name_ru"=>nil, "name_en"=>"Aegean Islands and Crete")
RivalRegion.create("rivals_id"=>2505, "name_ru"=>nil, "name_en"=>"Athens")
RivalRegion.create("rivals_id"=>2601, "name_ru"=>nil, "name_en"=>"Macedonia")
RivalRegion.create("rivals_id"=>2701, "name_ru"=>nil, "name_en"=>"Albania")
RivalRegion.create("rivals_id"=>2702, "name_ru"=>nil, "name_en"=>"Tirana")
RivalRegion.create("rivals_id"=>2801, "name_ru"=>nil, "name_en"=>"Vojvodina")
RivalRegion.create("rivals_id"=>2802, "name_ru"=>nil, "name_en"=>"Belgrade")
RivalRegion.create("rivals_id"=>2803, "name_ru"=>nil, "name_en"=>"Western Serbia")
RivalRegion.create("rivals_id"=>2804, "name_ru"=>nil, "name_en"=>"Southern and Eastern Serbia")
RivalRegion.create("rivals_id"=>2805, "name_ru"=>nil, "name_en"=>"Kosovo")
RivalRegion.create("rivals_id"=>2806, "name_ru"=>nil, "name_en"=>"Novi Sad")
RivalRegion.create("rivals_id"=>2807, "name_ru"=>nil, "name_en"=>"Niš")
RivalRegion.create("rivals_id"=>2901, "name_ru"=>nil, "name_en"=>"Lake Geneva")
RivalRegion.create("rivals_id"=>2902, "name_ru"=>nil, "name_en"=>"Espace Mittelland")
RivalRegion.create("rivals_id"=>2903, "name_ru"=>nil, "name_en"=>"Northwestern Switzerland")
RivalRegion.create("rivals_id"=>2904, "name_ru"=>nil, "name_en"=>"Zurich")
RivalRegion.create("rivals_id"=>2905, "name_ru"=>nil, "name_en"=>"Eastern Switzerland")
RivalRegion.create("rivals_id"=>2906, "name_ru"=>nil, "name_en"=>"Central Switzerland")
RivalRegion.create("rivals_id"=>2907, "name_ru"=>nil, "name_en"=>"Ticino")
RivalRegion.create("rivals_id"=>3001, "name_ru"=>nil, "name_en"=>"Montenegro")
RivalRegion.create("rivals_id"=>3101, "name_ru"=>nil, "name_en"=>"East Slovenia")
RivalRegion.create("rivals_id"=>3102, "name_ru"=>nil, "name_en"=>"West Slovenia")
RivalRegion.create("rivals_id"=>3201, "name_ru"=>nil, "name_en"=>"Continental Croatia")
RivalRegion.create("rivals_id"=>3202, "name_ru"=>nil, "name_en"=>"Adriatic Croatia")
RivalRegion.create("rivals_id"=>3301, "name_ru"=>nil, "name_en"=>"Federation of Bosnia and Herzegovina")
RivalRegion.create("rivals_id"=>3302, "name_ru"=>nil, "name_en"=>"Republika Srpska")
RivalRegion.create("rivals_id"=>3401, "name_ru"=>nil, "name_en"=>"North Korea")
RivalRegion.create("rivals_id"=>3501, "name_ru"=>nil, "name_en"=>"Yeongnam")
RivalRegion.create("rivals_id"=>3502, "name_ru"=>nil, "name_en"=>"Hoseo")
RivalRegion.create("rivals_id"=>3503, "name_ru"=>nil, "name_en"=>"Sudogwon")
RivalRegion.create("rivals_id"=>3504, "name_ru"=>nil, "name_en"=>"Honam")
RivalRegion.create("rivals_id"=>3505, "name_ru"=>nil, "name_en"=>"Gwandong")
RivalRegion.create("rivals_id"=>3601, "name_ru"=>nil, "name_en"=>"Hokkaido")
RivalRegion.create("rivals_id"=>3602, "name_ru"=>nil, "name_en"=>"Tōhoku")
RivalRegion.create("rivals_id"=>3603, "name_ru"=>nil, "name_en"=>"Kantō")
RivalRegion.create("rivals_id"=>3604, "name_ru"=>nil, "name_en"=>"Chūbu")
RivalRegion.create("rivals_id"=>3605, "name_ru"=>nil, "name_en"=>"Kansai")
RivalRegion.create("rivals_id"=>3606, "name_ru"=>nil, "name_en"=>"Chūgoku")
RivalRegion.create("rivals_id"=>3607, "name_ru"=>nil, "name_en"=>"Shikoku")
RivalRegion.create("rivals_id"=>3608, "name_ru"=>nil, "name_en"=>"Kyushu")
RivalRegion.create("rivals_id"=>3609, "name_ru"=>nil, "name_en"=>"Okinawa")
RivalRegion.create("rivals_id"=>3610, "name_ru"=>nil, "name_en"=>"Tokio")
RivalRegion.create("rivals_id"=>3701, "name_ru"=>nil, "name_en"=>"Liechtenstein")
RivalRegion.create("rivals_id"=>3801, "name_ru"=>nil, "name_en"=>"Alabama")
RivalRegion.create("rivals_id"=>3802, "name_ru"=>nil, "name_en"=>"Alaska")
RivalRegion.create("rivals_id"=>3803, "name_ru"=>nil, "name_en"=>"Arizona")
RivalRegion.create("rivals_id"=>3804, "name_ru"=>nil, "name_en"=>"Arkansas")
RivalRegion.create("rivals_id"=>3805, "name_ru"=>nil, "name_en"=>"California")
RivalRegion.create("rivals_id"=>3806, "name_ru"=>nil, "name_en"=>"Colorado")
RivalRegion.create("rivals_id"=>3807, "name_ru"=>nil, "name_en"=>"Connecticut")
RivalRegion.create("rivals_id"=>3808, "name_ru"=>nil, "name_en"=>"Delaware")
RivalRegion.create("rivals_id"=>3809, "name_ru"=>nil, "name_en"=>"Florida")
RivalRegion.create("rivals_id"=>3810, "name_ru"=>nil, "name_en"=>"Georgia")
RivalRegion.create("rivals_id"=>3811, "name_ru"=>nil, "name_en"=>"Hawaii")
RivalRegion.create("rivals_id"=>3812, "name_ru"=>nil, "name_en"=>"Idaho")
RivalRegion.create("rivals_id"=>3813, "name_ru"=>nil, "name_en"=>"Illinois")
RivalRegion.create("rivals_id"=>3814, "name_ru"=>nil, "name_en"=>"Indiana")
RivalRegion.create("rivals_id"=>3815, "name_ru"=>nil, "name_en"=>"Iowa")
RivalRegion.create("rivals_id"=>3816, "name_ru"=>nil, "name_en"=>"Kansas")
RivalRegion.create("rivals_id"=>3817, "name_ru"=>nil, "name_en"=>"Kentucky")
RivalRegion.create("rivals_id"=>3818, "name_ru"=>nil, "name_en"=>"Louisiana")
RivalRegion.create("rivals_id"=>3819, "name_ru"=>nil, "name_en"=>"Maine")
RivalRegion.create("rivals_id"=>3820, "name_ru"=>nil, "name_en"=>"Maryland")
RivalRegion.create("rivals_id"=>3821, "name_ru"=>nil, "name_en"=>"Massachusetts")
RivalRegion.create("rivals_id"=>3822, "name_ru"=>nil, "name_en"=>"Michigan")
RivalRegion.create("rivals_id"=>3823, "name_ru"=>nil, "name_en"=>"Minnesota")
RivalRegion.create("rivals_id"=>3824, "name_ru"=>nil, "name_en"=>"Mississippi")
RivalRegion.create("rivals_id"=>3825, "name_ru"=>nil, "name_en"=>"Missouri")
RivalRegion.create("rivals_id"=>3826, "name_ru"=>nil, "name_en"=>"Montana")
RivalRegion.create("rivals_id"=>3827, "name_ru"=>nil, "name_en"=>"Nebraska")
RivalRegion.create("rivals_id"=>3828, "name_ru"=>nil, "name_en"=>"Nevada")
RivalRegion.create("rivals_id"=>3829, "name_ru"=>nil, "name_en"=>"New Hampshire")
RivalRegion.create("rivals_id"=>3830, "name_ru"=>nil, "name_en"=>"New Jersey")
RivalRegion.create("rivals_id"=>3831, "name_ru"=>nil, "name_en"=>"New Mexico")
RivalRegion.create("rivals_id"=>3832, "name_ru"=>nil, "name_en"=>"New York State")
RivalRegion.create("rivals_id"=>3833, "name_ru"=>nil, "name_en"=>"North Carolina")
RivalRegion.create("rivals_id"=>3834, "name_ru"=>nil, "name_en"=>"North Dakota")
RivalRegion.create("rivals_id"=>3835, "name_ru"=>nil, "name_en"=>"Ohio")
RivalRegion.create("rivals_id"=>3836, "name_ru"=>nil, "name_en"=>"Oklahoma")
RivalRegion.create("rivals_id"=>3837, "name_ru"=>nil, "name_en"=>"Oregon")
RivalRegion.create("rivals_id"=>3838, "name_ru"=>nil, "name_en"=>"Pennsylvania")
RivalRegion.create("rivals_id"=>3839, "name_ru"=>nil, "name_en"=>"Rhode Island")
RivalRegion.create("rivals_id"=>3840, "name_ru"=>nil, "name_en"=>"South Carolina")
RivalRegion.create("rivals_id"=>3841, "name_ru"=>nil, "name_en"=>"South Dakota")
RivalRegion.create("rivals_id"=>3842, "name_ru"=>nil, "name_en"=>"Tennessee")
RivalRegion.create("rivals_id"=>3843, "name_ru"=>nil, "name_en"=>"Texas")
RivalRegion.create("rivals_id"=>3844, "name_ru"=>nil, "name_en"=>"Utah")
RivalRegion.create("rivals_id"=>3845, "name_ru"=>nil, "name_en"=>"Vermont")
RivalRegion.create("rivals_id"=>3846, "name_ru"=>nil, "name_en"=>"Virginia")
RivalRegion.create("rivals_id"=>3847, "name_ru"=>nil, "name_en"=>"Washington State")
RivalRegion.create("rivals_id"=>3848, "name_ru"=>nil, "name_en"=>"West Virginia")
RivalRegion.create("rivals_id"=>3849, "name_ru"=>nil, "name_en"=>"Wisconsin")
RivalRegion.create("rivals_id"=>3850, "name_ru"=>nil, "name_en"=>"Wyoming")
RivalRegion.create("rivals_id"=>3851, "name_ru"=>nil, "name_en"=>"Puerto Rico")
RivalRegion.create("rivals_id"=>3852, "name_ru"=>nil, "name_en"=>"Washington, D.C")
RivalRegion.create("rivals_id"=>3853, "name_ru"=>nil, "name_en"=>"New York")
RivalRegion.create("rivals_id"=>3854, "name_ru"=>nil, "name_en"=>"Los Angeles")
RivalRegion.create("rivals_id"=>3855, "name_ru"=>nil, "name_en"=>"Chicago")
RivalRegion.create("rivals_id"=>3856, "name_ru"=>nil, "name_en"=>"Houston")
RivalRegion.create("rivals_id"=>3857, "name_ru"=>nil, "name_en"=>"Midway Atoll")
RivalRegion.create("rivals_id"=>3858, "name_ru"=>nil, "name_en"=>"Philadelphia")
RivalRegion.create("rivals_id"=>3859, "name_ru"=>nil, "name_en"=>"Phoenix")
RivalRegion.create("rivals_id"=>3901, "name_ru"=>nil, "name_en"=>"British Columbia")
RivalRegion.create("rivals_id"=>3902, "name_ru"=>nil, "name_en"=>"Alberta")
RivalRegion.create("rivals_id"=>3903, "name_ru"=>nil, "name_en"=>"Saskatchewan")
RivalRegion.create("rivals_id"=>3904, "name_ru"=>nil, "name_en"=>"Manitoba")
RivalRegion.create("rivals_id"=>3905, "name_ru"=>nil, "name_en"=>"Ontario")
RivalRegion.create("rivals_id"=>3906, "name_ru"=>nil, "name_en"=>"Quebec")
RivalRegion.create("rivals_id"=>3907, "name_ru"=>nil, "name_en"=>"New Brunswick")
RivalRegion.create("rivals_id"=>3908, "name_ru"=>nil, "name_en"=>"Prince Edward Island")
RivalRegion.create("rivals_id"=>3909, "name_ru"=>nil, "name_en"=>"Nova Scotia")
RivalRegion.create("rivals_id"=>3910, "name_ru"=>nil, "name_en"=>"Newfoundland and Labrador")
RivalRegion.create("rivals_id"=>3911, "name_ru"=>nil, "name_en"=>"Yukon")
RivalRegion.create("rivals_id"=>3912, "name_ru"=>nil, "name_en"=>"Northwest Territories")
RivalRegion.create("rivals_id"=>3913, "name_ru"=>nil, "name_en"=>"Nunavut")
RivalRegion.create("rivals_id"=>3914, "name_ru"=>nil, "name_en"=>"Ottawa")
RivalRegion.create("rivals_id"=>3915, "name_ru"=>nil, "name_en"=>"Toronto")
RivalRegion.create("rivals_id"=>3916, "name_ru"=>nil, "name_en"=>"Montreal")
RivalRegion.create("rivals_id"=>4001, "name_ru"=>nil, "name_en"=>"Northern Netherlands")
RivalRegion.create("rivals_id"=>4002, "name_ru"=>nil, "name_en"=>"Eastern Netherlands")
RivalRegion.create("rivals_id"=>4003, "name_ru"=>nil, "name_en"=>"Western Netherlands")
RivalRegion.create("rivals_id"=>4004, "name_ru"=>nil, "name_en"=>"Southern Netherlands")
RivalRegion.create("rivals_id"=>4005, "name_ru"=>nil, "name_en"=>"Bonaire")
RivalRegion.create("rivals_id"=>4006, "name_ru"=>nil, "name_en"=>"Aruba")
RivalRegion.create("rivals_id"=>4007, "name_ru"=>nil, "name_en"=>"Curaçao")
RivalRegion.create("rivals_id"=>4008, "name_ru"=>nil, "name_en"=>"Amsterdam")
RivalRegion.create("rivals_id"=>4101, "name_ru"=>nil, "name_en"=>"Flemish Region")
RivalRegion.create("rivals_id"=>4102, "name_ru"=>nil, "name_en"=>"Wallonia")
RivalRegion.create("rivals_id"=>4103, "name_ru"=>nil, "name_en"=>"City of Brussels")
RivalRegion.create("rivals_id"=>4201, "name_ru"=>nil, "name_en"=>"Île-de-France")
RivalRegion.create("rivals_id"=>4202, "name_ru"=>nil, "name_en"=>"Centre-Val de Loire")
RivalRegion.create("rivals_id"=>4203, "name_ru"=>nil, "name_en"=>"Hauts-de-France")
RivalRegion.create("rivals_id"=>4204, "name_ru"=>nil, "name_en"=>"Grand Est")
RivalRegion.create("rivals_id"=>4205, "name_ru"=>nil, "name_en"=>"Brittany")
RivalRegion.create("rivals_id"=>4206, "name_ru"=>nil, "name_en"=>"Nouvelle-Aquitaine")
RivalRegion.create("rivals_id"=>4207, "name_ru"=>nil, "name_en"=>"Auvergne-Rhône-Alpes")
RivalRegion.create("rivals_id"=>4208, "name_ru"=>nil, "name_en"=>"Provence-Alpes-Côte d'Azur")
RivalRegion.create("rivals_id"=>4209, "name_ru"=>nil, "name_en"=>"French Guiana")
RivalRegion.create("rivals_id"=>4210, "name_ru"=>nil, "name_en"=>"New Caledonia")
RivalRegion.create("rivals_id"=>4211, "name_ru"=>nil, "name_en"=>"Mayotte")
RivalRegion.create("rivals_id"=>4212, "name_ru"=>nil, "name_en"=>"Paris")
RivalRegion.create("rivals_id"=>4213, "name_ru"=>nil, "name_en"=>"Normandy")
RivalRegion.create("rivals_id"=>4214, "name_ru"=>nil, "name_en"=>"Pays de la Loire")
RivalRegion.create("rivals_id"=>4215, "name_ru"=>nil, "name_en"=>"Bourgogne-Franche-Comté")
RivalRegion.create("rivals_id"=>4216, "name_ru"=>nil, "name_en"=>"Occitanie")
RivalRegion.create("rivals_id"=>4217, "name_ru"=>nil, "name_en"=>"Corsica")
RivalRegion.create("rivals_id"=>4218, "name_ru"=>nil, "name_en"=>"Guadeloupe")
RivalRegion.create("rivals_id"=>4219, "name_ru"=>nil, "name_en"=>"Martinique")
RivalRegion.create("rivals_id"=>4220, "name_ru"=>nil, "name_en"=>"Réunion")
RivalRegion.create("rivals_id"=>4221, "name_ru"=>nil, "name_en"=>"Lyon")
RivalRegion.create("rivals_id"=>4222, "name_ru"=>nil, "name_en"=>"Marseille")
RivalRegion.create("rivals_id"=>4223, "name_ru"=>nil, "name_en"=>"Toulouse")
RivalRegion.create("rivals_id"=>4301, "name_ru"=>nil, "name_en"=>"Galicia")
RivalRegion.create("rivals_id"=>4302, "name_ru"=>nil, "name_en"=>"Navarre")
RivalRegion.create("rivals_id"=>4303, "name_ru"=>nil, "name_en"=>"Community of Madrid")
RivalRegion.create("rivals_id"=>4304, "name_ru"=>nil, "name_en"=>"Balearic Islands")
RivalRegion.create("rivals_id"=>4305, "name_ru"=>nil, "name_en"=>"Andalusia")
RivalRegion.create("rivals_id"=>4306, "name_ru"=>nil, "name_en"=>"Canary Islands")
RivalRegion.create("rivals_id"=>4307, "name_ru"=>nil, "name_en"=>"Madrid")
RivalRegion.create("rivals_id"=>4308, "name_ru"=>nil, "name_en"=>"Barcelona")
RivalRegion.create("rivals_id"=>4309, "name_ru"=>nil, "name_en"=>"Catalonia")
RivalRegion.create("rivals_id"=>4310, "name_ru"=>nil, "name_en"=>"Valencian Community")
RivalRegion.create("rivals_id"=>4311, "name_ru"=>nil, "name_en"=>"Castile and León")
RivalRegion.create("rivals_id"=>4312, "name_ru"=>nil, "name_en"=>"Basque Country")
RivalRegion.create("rivals_id"=>4313, "name_ru"=>nil, "name_en"=>"Castilla-La Mancha")
RivalRegion.create("rivals_id"=>4314, "name_ru"=>nil, "name_en"=>"Region of Murcia")
RivalRegion.create("rivals_id"=>4315, "name_ru"=>nil, "name_en"=>"Aragon")
RivalRegion.create("rivals_id"=>4316, "name_ru"=>nil, "name_en"=>"Extremadura")
RivalRegion.create("rivals_id"=>4317, "name_ru"=>nil, "name_en"=>"Asturias")
RivalRegion.create("rivals_id"=>4318, "name_ru"=>nil, "name_en"=>"Cantabria")
RivalRegion.create("rivals_id"=>4319, "name_ru"=>nil, "name_en"=>"La Rioja")
RivalRegion.create("rivals_id"=>4320, "name_ru"=>nil, "name_en"=>"Valencia")
RivalRegion.create("rivals_id"=>4401, "name_ru"=>nil, "name_en"=>"Aosta Valley")
RivalRegion.create("rivals_id"=>4402, "name_ru"=>nil, "name_en"=>"Friuli-Venezia Giulia")
RivalRegion.create("rivals_id"=>4403, "name_ru"=>nil, "name_en"=>"Lazio")
RivalRegion.create("rivals_id"=>4404, "name_ru"=>nil, "name_en"=>"Calabria")
RivalRegion.create("rivals_id"=>4405, "name_ru"=>nil, "name_en"=>"Sicily")
RivalRegion.create("rivals_id"=>4406, "name_ru"=>nil, "name_en"=>"Sardinia")
RivalRegion.create("rivals_id"=>4407, "name_ru"=>nil, "name_en"=>"Rome")
RivalRegion.create("rivals_id"=>4408, "name_ru"=>nil, "name_en"=>"Milan")
RivalRegion.create("rivals_id"=>4409, "name_ru"=>nil, "name_en"=>"Abruzzo")
RivalRegion.create("rivals_id"=>4410, "name_ru"=>nil, "name_en"=>"Apulia")
RivalRegion.create("rivals_id"=>4411, "name_ru"=>nil, "name_en"=>"Basilicata")
RivalRegion.create("rivals_id"=>4412, "name_ru"=>nil, "name_en"=>"Campania")
RivalRegion.create("rivals_id"=>4413, "name_ru"=>nil, "name_en"=>"Emilia-Romagna")
RivalRegion.create("rivals_id"=>4414, "name_ru"=>nil, "name_en"=>"Liguria")
RivalRegion.create("rivals_id"=>4415, "name_ru"=>nil, "name_en"=>"Lombardy")
RivalRegion.create("rivals_id"=>4416, "name_ru"=>nil, "name_en"=>"Marche")
RivalRegion.create("rivals_id"=>4417, "name_ru"=>nil, "name_en"=>"Molise")
RivalRegion.create("rivals_id"=>4418, "name_ru"=>nil, "name_en"=>"Piedmont")
RivalRegion.create("rivals_id"=>4419, "name_ru"=>nil, "name_en"=>"Trentino-Alto Adige")
RivalRegion.create("rivals_id"=>4420, "name_ru"=>nil, "name_en"=>"Tuscany")
RivalRegion.create("rivals_id"=>4421, "name_ru"=>nil, "name_en"=>"Umbria")
RivalRegion.create("rivals_id"=>4422, "name_ru"=>nil, "name_en"=>"Veneto")
RivalRegion.create("rivals_id"=>4423, "name_ru"=>nil, "name_en"=>"Naples")
RivalRegion.create("rivals_id"=>4501, "name_ru"=>nil, "name_en"=>"Highlands of Scotland")
RivalRegion.create("rivals_id"=>4502, "name_ru"=>nil, "name_en"=>"North East Scotland")
RivalRegion.create("rivals_id"=>4503, "name_ru"=>nil, "name_en"=>"South West Scotland")
RivalRegion.create("rivals_id"=>4504, "name_ru"=>nil, "name_en"=>"East Scotland")
RivalRegion.create("rivals_id"=>4505, "name_ru"=>nil, "name_en"=>"North East England")
RivalRegion.create("rivals_id"=>4506, "name_ru"=>nil, "name_en"=>"North West England")
RivalRegion.create("rivals_id"=>4507, "name_ru"=>nil, "name_en"=>"Yorkshire and the Humber")
RivalRegion.create("rivals_id"=>4508, "name_ru"=>nil, "name_en"=>"East Midlands of England")
RivalRegion.create("rivals_id"=>4509, "name_ru"=>nil, "name_en"=>"West Midlands of England")
RivalRegion.create("rivals_id"=>4510, "name_ru"=>nil, "name_en"=>"East England")
RivalRegion.create("rivals_id"=>4511, "name_ru"=>nil, "name_en"=>"London")
RivalRegion.create("rivals_id"=>4512, "name_ru"=>nil, "name_en"=>"South East England")
RivalRegion.create("rivals_id"=>4513, "name_ru"=>nil, "name_en"=>"South West England")
RivalRegion.create("rivals_id"=>4514, "name_ru"=>nil, "name_en"=>"Wales")
RivalRegion.create("rivals_id"=>4515, "name_ru"=>nil, "name_en"=>"Northern Ireland")
RivalRegion.create("rivals_id"=>4516, "name_ru"=>nil, "name_en"=>"Isle of Man")
RivalRegion.create("rivals_id"=>4517, "name_ru"=>nil, "name_en"=>"Channel Islands")
RivalRegion.create("rivals_id"=>4518, "name_ru"=>nil, "name_en"=>"Gibraltar")
RivalRegion.create("rivals_id"=>4519, "name_ru"=>nil, "name_en"=>"Turks and Caicos Islands")
RivalRegion.create("rivals_id"=>4520, "name_ru"=>nil, "name_en"=>"Falkland Islands")
RivalRegion.create("rivals_id"=>4521, "name_ru"=>nil, "name_en"=>"Edinburgh")
RivalRegion.create("rivals_id"=>4522, "name_ru"=>nil, "name_en"=>"Cardiff")
RivalRegion.create("rivals_id"=>4523, "name_ru"=>nil, "name_en"=>"Belfast")
RivalRegion.create("rivals_id"=>4524, "name_ru"=>nil, "name_en"=>"Birmingham")
RivalRegion.create("rivals_id"=>4525, "name_ru"=>nil, "name_en"=>"Swansea")
RivalRegion.create("rivals_id"=>4526, "name_ru"=>nil, "name_en"=>"Leeds")
RivalRegion.create("rivals_id"=>4601, "name_ru"=>nil, "name_en"=>"Malta")
RivalRegion.create("rivals_id"=>4701, "name_ru"=>nil, "name_en"=>"Midland and West Ireland")
RivalRegion.create("rivals_id"=>4702, "name_ru"=>nil, "name_en"=>"South and East Ireland")
RivalRegion.create("rivals_id"=>4703, "name_ru"=>nil, "name_en"=>"Dublin")
RivalRegion.create("rivals_id"=>4801, "name_ru"=>nil, "name_en"=>"Luxembourg")
RivalRegion.create("rivals_id"=>4901, "name_ru"=>nil, "name_en"=>"Central Portugal")
RivalRegion.create("rivals_id"=>4902, "name_ru"=>nil, "name_en"=>"Azores")
RivalRegion.create("rivals_id"=>4903, "name_ru"=>nil, "name_en"=>"Madeira")
RivalRegion.create("rivals_id"=>4904, "name_ru"=>nil, "name_en"=>"North of Portugal")
RivalRegion.create("rivals_id"=>4905, "name_ru"=>nil, "name_en"=>"Algarve")
RivalRegion.create("rivals_id"=>4906, "name_ru"=>nil, "name_en"=>"Lisbon")
RivalRegion.create("rivals_id"=>4907, "name_ru"=>nil, "name_en"=>"Alentejo")
RivalRegion.create("rivals_id"=>5001, "name_ru"=>nil, "name_en"=>"Monaco")
RivalRegion.create("rivals_id"=>5101, "name_ru"=>nil, "name_en"=>"Batken Province")
RivalRegion.create("rivals_id"=>5102, "name_ru"=>nil, "name_en"=>"Jalal-Abad Province")
RivalRegion.create("rivals_id"=>5103, "name_ru"=>nil, "name_en"=>"Issyk Kul Province")
RivalRegion.create("rivals_id"=>5104, "name_ru"=>nil, "name_en"=>"Naryn Province")
RivalRegion.create("rivals_id"=>5105, "name_ru"=>nil, "name_en"=>"Osh Province")
RivalRegion.create("rivals_id"=>5106, "name_ru"=>nil, "name_en"=>"Talas Province")
RivalRegion.create("rivals_id"=>5107, "name_ru"=>nil, "name_en"=>"Chuy Province")
RivalRegion.create("rivals_id"=>5201, "name_ru"=>nil, "name_en"=>"Fergana Valley")
RivalRegion.create("rivals_id"=>5202, "name_ru"=>nil, "name_en"=>"North Uzbekistan")
RivalRegion.create("rivals_id"=>5203, "name_ru"=>nil, "name_en"=>"Samarkand and Bukhara")
RivalRegion.create("rivals_id"=>5204, "name_ru"=>nil, "name_en"=>"South Uzbekistan")
RivalRegion.create("rivals_id"=>5205, "name_ru"=>nil, "name_en"=>"Central Uzbekistan")
RivalRegion.create("rivals_id"=>5206, "name_ru"=>nil, "name_en"=>"Karakalpakstan")
RivalRegion.create("rivals_id"=>5401, "name_ru"=>nil, "name_en"=>"Northwest Argentina")
RivalRegion.create("rivals_id"=>5402, "name_ru"=>nil, "name_en"=>"Chaco")
RivalRegion.create("rivals_id"=>5403, "name_ru"=>nil, "name_en"=>"Mesopotamia")
RivalRegion.create("rivals_id"=>5404, "name_ru"=>nil, "name_en"=>"Cuyo")
RivalRegion.create("rivals_id"=>5405, "name_ru"=>nil, "name_en"=>"Central Sierras")
RivalRegion.create("rivals_id"=>5406, "name_ru"=>nil, "name_en"=>"Pampas")
RivalRegion.create("rivals_id"=>5407, "name_ru"=>nil, "name_en"=>"Dry Pampas")
RivalRegion.create("rivals_id"=>5408, "name_ru"=>nil, "name_en"=>"Patagonia")
RivalRegion.create("rivals_id"=>5409, "name_ru"=>nil, "name_en"=>"Buenos Aires")
RivalRegion.create("rivals_id"=>5410, "name_ru"=>nil, "name_en"=>"Cordoba")
RivalRegion.create("rivals_id"=>5411, "name_ru"=>nil, "name_en"=>"Rosario")
RivalRegion.create("rivals_id"=>5501, "name_ru"=>nil, "name_en"=>"Andhra Pradesh")
RivalRegion.create("rivals_id"=>5502, "name_ru"=>nil, "name_en"=>"Arunachal Pradesh")
RivalRegion.create("rivals_id"=>5503, "name_ru"=>nil, "name_en"=>"Assam")
RivalRegion.create("rivals_id"=>5504, "name_ru"=>nil, "name_en"=>"Bihar")
RivalRegion.create("rivals_id"=>5505, "name_ru"=>nil, "name_en"=>"Chhattisgarh")
RivalRegion.create("rivals_id"=>5506, "name_ru"=>nil, "name_en"=>"Goa")
RivalRegion.create("rivals_id"=>5507, "name_ru"=>nil, "name_en"=>"Gujarat")
RivalRegion.create("rivals_id"=>5508, "name_ru"=>nil, "name_en"=>"Haryana")
RivalRegion.create("rivals_id"=>5509, "name_ru"=>nil, "name_en"=>"Himachal Pradesh")
RivalRegion.create("rivals_id"=>5510, "name_ru"=>nil, "name_en"=>"Jammu and Kashmir")
RivalRegion.create("rivals_id"=>5511, "name_ru"=>nil, "name_en"=>"Jharkhand")
RivalRegion.create("rivals_id"=>5512, "name_ru"=>nil, "name_en"=>"Karnataka")
RivalRegion.create("rivals_id"=>5513, "name_ru"=>nil, "name_en"=>"Kerala")
RivalRegion.create("rivals_id"=>5514, "name_ru"=>nil, "name_en"=>"Madhya Pradesh")
RivalRegion.create("rivals_id"=>5515, "name_ru"=>nil, "name_en"=>"Maharashtra")
RivalRegion.create("rivals_id"=>5516, "name_ru"=>nil, "name_en"=>"Manipur")
RivalRegion.create("rivals_id"=>5517, "name_ru"=>nil, "name_en"=>"Meghalaya")
RivalRegion.create("rivals_id"=>5518, "name_ru"=>nil, "name_en"=>"Mizoram")
RivalRegion.create("rivals_id"=>5519, "name_ru"=>nil, "name_en"=>"Nagaland")
RivalRegion.create("rivals_id"=>5520, "name_ru"=>nil, "name_en"=>"Odisha")
RivalRegion.create("rivals_id"=>5521, "name_ru"=>nil, "name_en"=>"Indian Punjab")
RivalRegion.create("rivals_id"=>5522, "name_ru"=>nil, "name_en"=>"Rajasthan")
RivalRegion.create("rivals_id"=>5523, "name_ru"=>nil, "name_en"=>"Sikkim")
RivalRegion.create("rivals_id"=>5524, "name_ru"=>nil, "name_en"=>"Tamil Nadu")
RivalRegion.create("rivals_id"=>5525, "name_ru"=>nil, "name_en"=>"Tripura")
RivalRegion.create("rivals_id"=>5526, "name_ru"=>nil, "name_en"=>"Uttar Pradesh")
RivalRegion.create("rivals_id"=>5527, "name_ru"=>nil, "name_en"=>"Uttarakhand")
RivalRegion.create("rivals_id"=>5528, "name_ru"=>nil, "name_en"=>"West Bengal")
RivalRegion.create("rivals_id"=>5529, "name_ru"=>nil, "name_en"=>"Mumbai")
RivalRegion.create("rivals_id"=>5530, "name_ru"=>nil, "name_en"=>"Delhi")
RivalRegion.create("rivals_id"=>5601, "name_ru"=>nil, "name_en"=>"Amazonas")
RivalRegion.create("rivals_id"=>5602, "name_ru"=>nil, "name_en"=>"Bahia")
RivalRegion.create("rivals_id"=>5603, "name_ru"=>nil, "name_en"=>"Mato Grosso")
RivalRegion.create("rivals_id"=>5604, "name_ru"=>nil, "name_en"=>"Minas Gerais")
RivalRegion.create("rivals_id"=>5605, "name_ru"=>nil, "name_en"=>"Rio Grande do Sul")
RivalRegion.create("rivals_id"=>5606, "name_ru"=>nil, "name_en"=>"São Paulo")
RivalRegion.create("rivals_id"=>5607, "name_ru"=>nil, "name_en"=>"Rio de Janeiro")
RivalRegion.create("rivals_id"=>5608, "name_ru"=>nil, "name_en"=>"Acre")
RivalRegion.create("rivals_id"=>5609, "name_ru"=>nil, "name_en"=>"Alagoas")
RivalRegion.create("rivals_id"=>5610, "name_ru"=>nil, "name_en"=>"Amapá")
RivalRegion.create("rivals_id"=>5611, "name_ru"=>nil, "name_en"=>"Ceará")
RivalRegion.create("rivals_id"=>5612, "name_ru"=>nil, "name_en"=>"Federal District")
RivalRegion.create("rivals_id"=>5613, "name_ru"=>nil, "name_en"=>"Espírito Santo")
RivalRegion.create("rivals_id"=>5614, "name_ru"=>nil, "name_en"=>"Goiás")
RivalRegion.create("rivals_id"=>5615, "name_ru"=>nil, "name_en"=>"Maranhão")
RivalRegion.create("rivals_id"=>5616, "name_ru"=>nil, "name_en"=>"Mato Grosso do Sul")
RivalRegion.create("rivals_id"=>5617, "name_ru"=>nil, "name_en"=>"Pará")
RivalRegion.create("rivals_id"=>5618, "name_ru"=>nil, "name_en"=>"Paraíba")
RivalRegion.create("rivals_id"=>5619, "name_ru"=>nil, "name_en"=>"Paraná")
RivalRegion.create("rivals_id"=>5620, "name_ru"=>nil, "name_en"=>"Pernambuco")
RivalRegion.create("rivals_id"=>5621, "name_ru"=>nil, "name_en"=>"Piauí")
RivalRegion.create("rivals_id"=>5622, "name_ru"=>nil, "name_en"=>"State of Rio de Janeiro")
RivalRegion.create("rivals_id"=>5623, "name_ru"=>nil, "name_en"=>"Rio Grande do Norte")
RivalRegion.create("rivals_id"=>5624, "name_ru"=>nil, "name_en"=>"Rondônia")
RivalRegion.create("rivals_id"=>5625, "name_ru"=>nil, "name_en"=>"Roraima")
RivalRegion.create("rivals_id"=>5626, "name_ru"=>nil, "name_en"=>"Santa Catarina")
RivalRegion.create("rivals_id"=>5627, "name_ru"=>nil, "name_en"=>"State of São Paulo")
RivalRegion.create("rivals_id"=>5628, "name_ru"=>nil, "name_en"=>"Sergipe")
RivalRegion.create("rivals_id"=>5629, "name_ru"=>nil, "name_en"=>"Tocantins")
RivalRegion.create("rivals_id"=>5630, "name_ru"=>nil, "name_en"=>"Brasilia")
RivalRegion.create("rivals_id"=>5631, "name_ru"=>nil, "name_en"=>"Salvador")
RivalRegion.create("rivals_id"=>5632, "name_ru"=>nil, "name_en"=>"Fortaleza")
RivalRegion.create("rivals_id"=>5633, "name_ru"=>nil, "name_en"=>"Belo Horizonte")
RivalRegion.create("rivals_id"=>5634, "name_ru"=>nil, "name_en"=>"Manaus")
RivalRegion.create("rivals_id"=>5701, "name_ru"=>nil, "name_en"=>"Balochistan")
RivalRegion.create("rivals_id"=>5702, "name_ru"=>nil, "name_en"=>"Khyber Pakhtunkhwa")
RivalRegion.create("rivals_id"=>5703, "name_ru"=>nil, "name_en"=>"Punjab")
RivalRegion.create("rivals_id"=>5704, "name_ru"=>nil, "name_en"=>"Sindh")
RivalRegion.create("rivals_id"=>5705, "name_ru"=>nil, "name_en"=>"Tribal Areas")
RivalRegion.create("rivals_id"=>5706, "name_ru"=>nil, "name_en"=>"Azad Kashmir")
RivalRegion.create("rivals_id"=>5707, "name_ru"=>nil, "name_en"=>"Gilgit–Baltistan")
RivalRegion.create("rivals_id"=>5801, "name_ru"=>nil, "name_en"=>"Tarapacá")
RivalRegion.create("rivals_id"=>5802, "name_ru"=>nil, "name_en"=>"Antofagasta")
RivalRegion.create("rivals_id"=>5803, "name_ru"=>nil, "name_en"=>"Atacama")
RivalRegion.create("rivals_id"=>5804, "name_ru"=>nil, "name_en"=>"Coquimbo")
RivalRegion.create("rivals_id"=>5805, "name_ru"=>nil, "name_en"=>"Valparaíso")
RivalRegion.create("rivals_id"=>5806, "name_ru"=>nil, "name_en"=>"Libertador General")
RivalRegion.create("rivals_id"=>5807, "name_ru"=>nil, "name_en"=>"Maule")
RivalRegion.create("rivals_id"=>5808, "name_ru"=>nil, "name_en"=>"Bío Bío")
RivalRegion.create("rivals_id"=>5809, "name_ru"=>nil, "name_en"=>"Araucanía")
RivalRegion.create("rivals_id"=>5810, "name_ru"=>nil, "name_en"=>"Los Lagos")
RivalRegion.create("rivals_id"=>5811, "name_ru"=>nil, "name_en"=>"Aisén")
RivalRegion.create("rivals_id"=>5812, "name_ru"=>nil, "name_en"=>"Magallanes")
RivalRegion.create("rivals_id"=>5813, "name_ru"=>nil, "name_en"=>"Santiago Metropolitan")
RivalRegion.create("rivals_id"=>5814, "name_ru"=>nil, "name_en"=>"Los Ríos")
RivalRegion.create("rivals_id"=>5815, "name_ru"=>nil, "name_en"=>"Arica and Parinacota")
RivalRegion.create("rivals_id"=>5816, "name_ru"=>nil, "name_en"=>"Santiago")
RivalRegion.create("rivals_id"=>5817, "name_ru"=>nil, "name_en"=>"Viña del Mar")
RivalRegion.create("rivals_id"=>6001, "name_ru"=>nil, "name_en"=>"Peru")
RivalRegion.create("rivals_id"=>6002, "name_ru"=>nil, "name_en"=>"Lima")
RivalRegion.create("rivals_id"=>6101, "name_ru"=>nil, "name_en"=>"Colombia")
RivalRegion.create("rivals_id"=>6102, "name_ru"=>nil, "name_en"=>"Bogota")
RivalRegion.create("rivals_id"=>6201, "name_ru"=>nil, "name_en"=>"Venezuela")
RivalRegion.create("rivals_id"=>6202, "name_ru"=>nil, "name_en"=>"Caracas")
RivalRegion.create("rivals_id"=>6301, "name_ru"=>nil, "name_en"=>"Philippines")
RivalRegion.create("rivals_id"=>6302, "name_ru"=>nil, "name_en"=>"Manila")
RivalRegion.create("rivals_id"=>6401, "name_ru"=>nil, "name_en"=>"Northern Iraq")
RivalRegion.create("rivals_id"=>6402, "name_ru"=>nil, "name_en"=>"Central Iraq")
RivalRegion.create("rivals_id"=>6403, "name_ru"=>nil, "name_en"=>"Middle Euphrates")
RivalRegion.create("rivals_id"=>6404, "name_ru"=>nil, "name_en"=>"Southern Iraq")
RivalRegion.create("rivals_id"=>6501, "name_ru"=>nil, "name_en"=>"Iranian Azerbaijan")
RivalRegion.create("rivals_id"=>6502, "name_ru"=>nil, "name_en"=>"Iranian Caspian Coast")
RivalRegion.create("rivals_id"=>6503, "name_ru"=>nil, "name_en"=>"Iranian Mountains")
RivalRegion.create("rivals_id"=>6504, "name_ru"=>nil, "name_en"=>"Iranian Persian Coast")
RivalRegion.create("rivals_id"=>6505, "name_ru"=>nil, "name_en"=>"Iranian Desert")
RivalRegion.create("rivals_id"=>6506, "name_ru"=>nil, "name_en"=>"Tehran")
RivalRegion.create("rivals_id"=>6601, "name_ru"=>nil, "name_en"=>"North China")
RivalRegion.create("rivals_id"=>6602, "name_ru"=>nil, "name_en"=>"Northeast China")
RivalRegion.create("rivals_id"=>6603, "name_ru"=>nil, "name_en"=>"East China")
RivalRegion.create("rivals_id"=>6604, "name_ru"=>nil, "name_en"=>"South Central China")
RivalRegion.create("rivals_id"=>6605, "name_ru"=>nil, "name_en"=>"Southwest China")
RivalRegion.create("rivals_id"=>6606, "name_ru"=>nil, "name_en"=>"Northwest China")
RivalRegion.create("rivals_id"=>6607, "name_ru"=>nil, "name_en"=>"Beijing")
RivalRegion.create("rivals_id"=>6701, "name_ru"=>nil, "name_en"=>"Sinai")
RivalRegion.create("rivals_id"=>6702, "name_ru"=>nil, "name_en"=>"Lower Egypt")
RivalRegion.create("rivals_id"=>6703, "name_ru"=>nil, "name_en"=>"Western Desert")
RivalRegion.create("rivals_id"=>6704, "name_ru"=>nil, "name_en"=>"Upper Egypt")
RivalRegion.create("rivals_id"=>6705, "name_ru"=>nil, "name_en"=>"Red Sea Coast")
RivalRegion.create("rivals_id"=>6706, "name_ru"=>nil, "name_en"=>"Middle Egypt")
RivalRegion.create("rivals_id"=>6707, "name_ru"=>nil, "name_en"=>"Cairo")
RivalRegion.create("rivals_id"=>6801, "name_ru"=>nil, "name_en"=>"Andorra")
RivalRegion.create("rivals_id"=>6901, "name_ru"=>nil, "name_en"=>"Vatican City")
RivalRegion.create("rivals_id"=>7001, "name_ru"=>nil, "name_en"=>"San Marino")
RivalRegion.create("rivals_id"=>7101, "name_ru"=>nil, "name_en"=>"Order of Malta")
RivalRegion.create("rivals_id"=>7301, "name_ru"=>nil, "name_en"=>"Gorno-Badakhshan AP")
RivalRegion.create("rivals_id"=>7302, "name_ru"=>nil, "name_en"=>"Sughd Province")
RivalRegion.create("rivals_id"=>7303, "name_ru"=>nil, "name_en"=>"Khatlon Province")
RivalRegion.create("rivals_id"=>7304, "name_ru"=>nil, "name_en"=>"Republican Subordination")
RivalRegion.create("rivals_id"=>7401, "name_ru"=>nil, "name_en"=>"South Australia")
RivalRegion.create("rivals_id"=>7402, "name_ru"=>nil, "name_en"=>"Western Australia")
RivalRegion.create("rivals_id"=>7403, "name_ru"=>nil, "name_en"=>"Northern Territory")
RivalRegion.create("rivals_id"=>7404, "name_ru"=>nil, "name_en"=>"Queensland")
RivalRegion.create("rivals_id"=>7405, "name_ru"=>nil, "name_en"=>"New South Wales")
RivalRegion.create("rivals_id"=>7406, "name_ru"=>nil, "name_en"=>"Victoria")
RivalRegion.create("rivals_id"=>7407, "name_ru"=>nil, "name_en"=>"Tasmania")
RivalRegion.create("rivals_id"=>7408, "name_ru"=>nil, "name_en"=>"Canberra")
RivalRegion.create("rivals_id"=>7409, "name_ru"=>nil, "name_en"=>"Melbourne")
RivalRegion.create("rivals_id"=>7410, "name_ru"=>nil, "name_en"=>"Sydney")
RivalRegion.create("rivals_id"=>7501, "name_ru"=>nil, "name_en"=>"UAE")
RivalRegion.create("rivals_id"=>7601, "name_ru"=>nil, "name_en"=>"Yemen")
RivalRegion.create("rivals_id"=>7801, "name_ru"=>nil, "name_en"=>"West Saudi Arabia")
RivalRegion.create("rivals_id"=>7802, "name_ru"=>nil, "name_en"=>"East Saudi Arabia")
RivalRegion.create("rivals_id"=>7803, "name_ru"=>nil, "name_en"=>"Mecca")
RivalRegion.create("rivals_id"=>7901, "name_ru"=>nil, "name_en"=>"Singapore")
RivalRegion.create("rivals_id"=>8101, "name_ru"=>nil, "name_en"=>"Northwest Mexico")
RivalRegion.create("rivals_id"=>8102, "name_ru"=>nil, "name_en"=>"Northeast Mexico")
RivalRegion.create("rivals_id"=>8103, "name_ru"=>nil, "name_en"=>"West Mexico")
RivalRegion.create("rivals_id"=>8104, "name_ru"=>nil, "name_en"=>"East Mexico")
RivalRegion.create("rivals_id"=>8105, "name_ru"=>nil, "name_en"=>"Northсentral Mexico")
RivalRegion.create("rivals_id"=>8106, "name_ru"=>nil, "name_en"=>"Southсentral Mexico")
RivalRegion.create("rivals_id"=>8107, "name_ru"=>nil, "name_en"=>"Southeast Mexico")
RivalRegion.create("rivals_id"=>8108, "name_ru"=>nil, "name_en"=>"Southwest Mexico")
RivalRegion.create("rivals_id"=>8109, "name_ru"=>nil, "name_en"=>"Mexico City")
RivalRegion.create("rivals_id"=>8110, "name_ru"=>nil, "name_en"=>"Guadalajara")
RivalRegion.create("rivals_id"=>8111, "name_ru"=>nil, "name_en"=>"Puebla (city)")
RivalRegion.create("rivals_id"=>8112, "name_ru"=>nil, "name_en"=>"Ciudad Juárez")
RivalRegion.create("rivals_id"=>8201, "name_ru"=>nil, "name_en"=>"North Island")
RivalRegion.create("rivals_id"=>8202, "name_ru"=>nil, "name_en"=>"South Island")
RivalRegion.create("rivals_id"=>8203, "name_ru"=>nil, "name_en"=>"Wellington")
RivalRegion.create("rivals_id"=>8301, "name_ru"=>nil, "name_en"=>"Cuba")
RivalRegion.create("rivals_id"=>8302, "name_ru"=>nil, "name_en"=>"Havana")
RivalRegion.create("rivals_id"=>8401, "name_ru"=>nil, "name_en"=>"Belize")
RivalRegion.create("rivals_id"=>8501, "name_ru"=>nil, "name_en"=>"Guatemala")
RivalRegion.create("rivals_id"=>8601, "name_ru"=>nil, "name_en"=>"Honduras")
RivalRegion.create("rivals_id"=>8701, "name_ru"=>nil, "name_en"=>"El Salvador")
RivalRegion.create("rivals_id"=>8801, "name_ru"=>nil, "name_en"=>"Nicaragua")
RivalRegion.create("rivals_id"=>8901, "name_ru"=>nil, "name_en"=>"Costa Rica")
RivalRegion.create("rivals_id"=>9001, "name_ru"=>nil, "name_en"=>"Panama")
RivalRegion.create("rivals_id"=>9101, "name_ru"=>nil, "name_en"=>"Bahamas")
RivalRegion.create("rivals_id"=>9201, "name_ru"=>nil, "name_en"=>"Jamaica")
RivalRegion.create("rivals_id"=>9301, "name_ru"=>nil, "name_en"=>"Dominican Republic")
RivalRegion.create("rivals_id"=>9401, "name_ru"=>nil, "name_en"=>"Haiti")
RivalRegion.create("rivals_id"=>9501, "name_ru"=>nil, "name_en"=>"Guyana")
RivalRegion.create("rivals_id"=>9601, "name_ru"=>nil, "name_en"=>"Suriname")
RivalRegion.create("rivals_id"=>9701, "name_ru"=>nil, "name_en"=>"Ecuador")
RivalRegion.create("rivals_id"=>9801, "name_ru"=>nil, "name_en"=>"Bolivia")
RivalRegion.create("rivals_id"=>9901, "name_ru"=>nil, "name_en"=>"Paraguay")
RivalRegion.create("rivals_id"=>10001, "name_ru"=>nil, "name_en"=>"Uruguay")
RivalRegion.create("rivals_id"=>10201, "name_ru"=>nil, "name_en"=>"Kuwait")
RivalRegion.create("rivals_id"=>10301, "name_ru"=>nil, "name_en"=>"Jordan")
RivalRegion.create("rivals_id"=>10401, "name_ru"=>nil, "name_en"=>"Northern Mongolia")
RivalRegion.create("rivals_id"=>10402, "name_ru"=>nil, "name_en"=>"Eastern Mongolia")
RivalRegion.create("rivals_id"=>10403, "name_ru"=>nil, "name_en"=>"Altai Mountains")
RivalRegion.create("rivals_id"=>10404, "name_ru"=>nil, "name_en"=>"Gobi Desert")
RivalRegion.create("rivals_id"=>10405, "name_ru"=>nil, "name_en"=>"Central Mongolia")
RivalRegion.create("rivals_id"=>10501, "name_ru"=>nil, "name_en"=>"Northern Vietnam")
RivalRegion.create("rivals_id"=>10502, "name_ru"=>nil, "name_en"=>"Southern Vietnam")
RivalRegion.create("rivals_id"=>10601, "name_ru"=>nil, "name_en"=>"Taiwan")
RivalRegion.create("rivals_id"=>10701, "name_ru"=>nil, "name_en"=>"Qatar")
RivalRegion.create("rivals_id"=>10702, "name_ru"=>nil, "name_en"=>"Doha")
RivalRegion.create("rivals_id"=>10801, "name_ru"=>nil, "name_en"=>"Oman")
RivalRegion.create("rivals_id"=>10901, "name_ru"=>nil, "name_en"=>"Bahrain")
RivalRegion.create("rivals_id"=>11001, "name_ru"=>nil, "name_en"=>"Sudan")
RivalRegion.create("rivals_id"=>11101, "name_ru"=>nil, "name_en"=>"Eritrea")
RivalRegion.create("rivals_id"=>11201, "name_ru"=>nil, "name_en"=>"Djibouti")
RivalRegion.create("rivals_id"=>11301, "name_ru"=>nil, "name_en"=>"Ethiopia")
RivalRegion.create("rivals_id"=>11401, "name_ru"=>nil, "name_en"=>"Somalia")
RivalRegion.create("rivals_id"=>11501, "name_ru"=>nil, "name_en"=>"Madagascar")
RivalRegion.create("rivals_id"=>11601, "name_ru"=>nil, "name_en"=>"Mozambique")
RivalRegion.create("rivals_id"=>11701, "name_ru"=>nil, "name_en"=>"Swaziland")
RivalRegion.create("rivals_id"=>11801, "name_ru"=>nil, "name_en"=>"Lesotho")
RivalRegion.create("rivals_id"=>11901, "name_ru"=>nil, "name_en"=>"Zimbabwe")
RivalRegion.create("rivals_id"=>12001, "name_ru"=>nil, "name_en"=>"Botswana")
RivalRegion.create("rivals_id"=>12002, "name_ru"=>nil, "name_en"=>"Jwaneng")
RivalRegion.create("rivals_id"=>12101, "name_ru"=>nil, "name_en"=>"Namibia")
RivalRegion.create("rivals_id"=>12201, "name_ru"=>nil, "name_en"=>"Angola")
RivalRegion.create("rivals_id"=>12301, "name_ru"=>nil, "name_en"=>"Zambia")
RivalRegion.create("rivals_id"=>12401, "name_ru"=>nil, "name_en"=>"Malawi")
RivalRegion.create("rivals_id"=>12501, "name_ru"=>nil, "name_en"=>"Tanzania")
RivalRegion.create("rivals_id"=>12601, "name_ru"=>nil, "name_en"=>"Burundi")
RivalRegion.create("rivals_id"=>12701, "name_ru"=>nil, "name_en"=>"Rwanda")
RivalRegion.create("rivals_id"=>12801, "name_ru"=>nil, "name_en"=>"DR of the Congo")
RivalRegion.create("rivals_id"=>12802, "name_ru"=>nil, "name_en"=>"Kinshasa")
RivalRegion.create("rivals_id"=>12901, "name_ru"=>nil, "name_en"=>"Republic of the Congo")
RivalRegion.create("rivals_id"=>13001, "name_ru"=>nil, "name_en"=>"Gabon")
RivalRegion.create("rivals_id"=>13101, "name_ru"=>nil, "name_en"=>"Equatorial Guinea")
RivalRegion.create("rivals_id"=>13201, "name_ru"=>nil, "name_en"=>"Cameroon")
RivalRegion.create("rivals_id"=>13301, "name_ru"=>nil, "name_en"=>"Central African Republic")
RivalRegion.create("rivals_id"=>13401, "name_ru"=>nil, "name_en"=>"South Sudan")
RivalRegion.create("rivals_id"=>13501, "name_ru"=>nil, "name_en"=>"Chad")
RivalRegion.create("rivals_id"=>13601, "name_ru"=>nil, "name_en"=>"Nigeria")
RivalRegion.create("rivals_id"=>13602, "name_ru"=>nil, "name_en"=>"Lagos")
RivalRegion.create("rivals_id"=>13701, "name_ru"=>nil, "name_en"=>"Benin")
RivalRegion.create("rivals_id"=>13801, "name_ru"=>nil, "name_en"=>"Togo")
RivalRegion.create("rivals_id"=>13901, "name_ru"=>nil, "name_en"=>"Ghana")
RivalRegion.create("rivals_id"=>14001, "name_ru"=>nil, "name_en"=>"Côte d'Ivoire")
RivalRegion.create("rivals_id"=>14101, "name_ru"=>nil, "name_en"=>"Liberia")
RivalRegion.create("rivals_id"=>14201, "name_ru"=>nil, "name_en"=>"Sierra Leone")
RivalRegion.create("rivals_id"=>14301, "name_ru"=>nil, "name_en"=>"Guinea")
RivalRegion.create("rivals_id"=>14401, "name_ru"=>nil, "name_en"=>"Guinea")
RivalRegion.create("rivals_id"=>14501, "name_ru"=>nil, "name_en"=>"Senegal")
RivalRegion.create("rivals_id"=>14601, "name_ru"=>nil, "name_en"=>"Gambia")
RivalRegion.create("rivals_id"=>14701, "name_ru"=>nil, "name_en"=>"Mali")
RivalRegion.create("rivals_id"=>14801, "name_ru"=>nil, "name_en"=>"Burkina Faso")
RivalRegion.create("rivals_id"=>14901, "name_ru"=>nil, "name_en"=>"Niger")
RivalRegion.create("rivals_id"=>15001, "name_ru"=>nil, "name_en"=>"Libya")
RivalRegion.create("rivals_id"=>15002, "name_ru"=>nil, "name_en"=>"Tripoli")
RivalRegion.create("rivals_id"=>15101, "name_ru"=>nil, "name_en"=>"Tunisia")
RivalRegion.create("rivals_id"=>15102, "name_ru"=>nil, "name_en"=>"Tunis")
RivalRegion.create("rivals_id"=>15201, "name_ru"=>nil, "name_en"=>"Algeria")
RivalRegion.create("rivals_id"=>15202, "name_ru"=>nil, "name_en"=>"Algiers")
RivalRegion.create("rivals_id"=>15301, "name_ru"=>nil, "name_en"=>"Mauritania")
RivalRegion.create("rivals_id"=>15401, "name_ru"=>nil, "name_en"=>"Morocco")
RivalRegion.create("rivals_id"=>15501, "name_ru"=>nil, "name_en"=>"Limpopo")
RivalRegion.create("rivals_id"=>15502, "name_ru"=>nil, "name_en"=>"Mpumalanga")
RivalRegion.create("rivals_id"=>15503, "name_ru"=>nil, "name_en"=>"Gauteng")
RivalRegion.create("rivals_id"=>15504, "name_ru"=>nil, "name_en"=>"North West")
RivalRegion.create("rivals_id"=>15505, "name_ru"=>nil, "name_en"=>"Free State")
RivalRegion.create("rivals_id"=>15506, "name_ru"=>nil, "name_en"=>"KwaZulu-Natal")
RivalRegion.create("rivals_id"=>15507, "name_ru"=>nil, "name_en"=>"Eastern Cape")
RivalRegion.create("rivals_id"=>15508, "name_ru"=>nil, "name_en"=>"Northern Cape")
RivalRegion.create("rivals_id"=>15509, "name_ru"=>nil, "name_en"=>"Western Cape")
RivalRegion.create("rivals_id"=>15510, "name_ru"=>nil, "name_en"=>"Johannesburg")
RivalRegion.create("rivals_id"=>15601, "name_ru"=>nil, "name_en"=>"Kenya")
RivalRegion.create("rivals_id"=>15701, "name_ru"=>nil, "name_en"=>"Uganda")
RivalRegion.create("rivals_id"=>15801, "name_ru"=>nil, "name_en"=>"Ahal Province")
RivalRegion.create("rivals_id"=>15802, "name_ru"=>nil, "name_en"=>"Balkan Province")
RivalRegion.create("rivals_id"=>15803, "name_ru"=>nil, "name_en"=>"Daşoguz Province")
RivalRegion.create("rivals_id"=>15804, "name_ru"=>nil, "name_en"=>"Lebap Province")
RivalRegion.create("rivals_id"=>15805, "name_ru"=>nil, "name_en"=>"Mary Province")
RivalRegion.create("rivals_id"=>16001, "name_ru"=>nil, "name_en"=>"Aragatsotn Province")
RivalRegion.create("rivals_id"=>16002, "name_ru"=>nil, "name_en"=>"Armavir Province")
RivalRegion.create("rivals_id"=>16003, "name_ru"=>nil, "name_en"=>"Ararat Province")
RivalRegion.create("rivals_id"=>16004, "name_ru"=>nil, "name_en"=>"Vayots Dzor Province")
RivalRegion.create("rivals_id"=>16005, "name_ru"=>nil, "name_en"=>"Gegharkunik Province")
RivalRegion.create("rivals_id"=>16006, "name_ru"=>nil, "name_en"=>"Kotayk Province")
RivalRegion.create("rivals_id"=>16007, "name_ru"=>nil, "name_en"=>"Lori Province")
RivalRegion.create("rivals_id"=>16008, "name_ru"=>nil, "name_en"=>"Syunik Province")
RivalRegion.create("rivals_id"=>16009, "name_ru"=>nil, "name_en"=>"Tavush Province")
RivalRegion.create("rivals_id"=>16010, "name_ru"=>nil, "name_en"=>"Shirak Province")
RivalRegion.create("rivals_id"=>16011, "name_ru"=>nil, "name_en"=>"Vagharshapat")
RivalRegion.create("rivals_id"=>16101, "name_ru"=>nil, "name_en"=>"Northern Afghanistan")
RivalRegion.create("rivals_id"=>16102, "name_ru"=>nil, "name_en"=>"Eastern Afghanistan")
RivalRegion.create("rivals_id"=>16103, "name_ru"=>nil, "name_en"=>"Southern Afghanistan")
RivalRegion.create("rivals_id"=>16104, "name_ru"=>nil, "name_en"=>"Southwestern Afghanistan")
RivalRegion.create("rivals_id"=>16105, "name_ru"=>nil, "name_en"=>"Western Afghanistan")
RivalRegion.create("rivals_id"=>16301, "name_ru"=>nil, "name_en"=>"Nepal")
RivalRegion.create("rivals_id"=>16401, "name_ru"=>nil, "name_en"=>"Bhutan")
RivalRegion.create("rivals_id"=>16501, "name_ru"=>nil, "name_en"=>"Bangladesh")
RivalRegion.create("rivals_id"=>16601, "name_ru"=>nil, "name_en"=>"Thailand")
RivalRegion.create("rivals_id"=>16701, "name_ru"=>nil, "name_en"=>"Burma")
RivalRegion.create("rivals_id"=>16801, "name_ru"=>nil, "name_en"=>"Brunei")
RivalRegion.create("rivals_id"=>16901, "name_ru"=>nil, "name_en"=>"Cambodia")
RivalRegion.create("rivals_id"=>17001, "name_ru"=>nil, "name_en"=>"Malaysia")
RivalRegion.create("rivals_id"=>17101, "name_ru"=>nil, "name_en"=>"Laos")
RivalRegion.create("rivals_id"=>17201, "name_ru"=>nil, "name_en"=>"Bali")
RivalRegion.create("rivals_id"=>17202, "name_ru"=>nil, "name_en"=>"Java")
RivalRegion.create("rivals_id"=>17203, "name_ru"=>nil, "name_en"=>"Jakarta")
RivalRegion.create("rivals_id"=>17204, "name_ru"=>nil, "name_en"=>"Borneo")
RivalRegion.create("rivals_id"=>17205, "name_ru"=>nil, "name_en"=>"Sulawesi")
RivalRegion.create("rivals_id"=>17206, "name_ru"=>nil, "name_en"=>"Nusa Tenggara")
RivalRegion.create("rivals_id"=>17207, "name_ru"=>nil, "name_en"=>"Sumatra")
RivalRegion.create("rivals_id"=>17208, "name_ru"=>nil, "name_en"=>"Maluku")
RivalRegion.create("rivals_id"=>17209, "name_ru"=>nil, "name_en"=>"North Maluku")
RivalRegion.create("rivals_id"=>17210, "name_ru"=>nil, "name_en"=>"Papua")
RivalRegion.create("rivals_id"=>17211, "name_ru"=>nil, "name_en"=>"Timor")
RivalRegion.create("rivals_id"=>17212, "name_ru"=>nil, "name_en"=>"Grasberg")
RivalRegion.create("rivals_id"=>17213, "name_ru"=>nil, "name_en"=>"Surabaya")
RivalRegion.create("rivals_id"=>17301, "name_ru"=>nil, "name_en"=>"Papua New Guinea")
RivalRegion.create("rivals_id"=>17401, "name_ru"=>nil, "name_en"=>"Sri Lanka")
RivalRegion.create("rivals_id"=>17501, "name_ru"=>nil, "name_en"=>"Maldives")
RivalRegion.create("rivals_id"=>17601, "name_ru"=>nil, "name_en"=>"Vanuatu")
RivalRegion.create("rivals_id"=>17701, "name_ru"=>nil, "name_en"=>"Solomon Islands")
RivalRegion.create("rivals_id"=>17801, "name_ru"=>nil, "name_en"=>"Fiji")
RivalRegion.create("rivals_id"=>17901, "name_ru"=>nil, "name_en"=>"Cape Verde")
RivalRegion.create("rivals_id"=>18001, "name_ru"=>nil, "name_en"=>"Trinidad and Tobago")
RivalRegion.create("rivals_id"=>18101, "name_ru"=>nil, "name_en"=>"Mauritius")
RivalRegion.create("rivals_id"=>18201, "name_ru"=>nil, "name_en"=>"Samoa")
RivalRegion.create("rivals_id"=>18301, "name_ru"=>nil, "name_en"=>"Comoros")
RivalRegion.create("rivals_id"=>18401, "name_ru"=>nil, "name_en"=>"Barbados")
RivalRegion.create("rivals_id"=>18501, "name_ru"=>nil, "name_en"=>"São Tomé and Príncipe")
RivalRegion.create("rivals_id"=>18601, "name_ru"=>nil, "name_en"=>"Nauru")
RivalRegion.create("rivals_id"=>18701, "name_ru"=>nil, "name_en"=>"Tuvalu")
RivalRegion.create("rivals_id"=>18801, "name_ru"=>nil, "name_en"=>"Grenada")
RivalRegion.create("rivals_id"=>18901, "name_ru"=>nil, "name_en"=>"Palau")
RivalRegion.create("rivals_id"=>19001, "name_ru"=>nil, "name_en"=>"Kiribati")
RivalRegion.create("rivals_id"=>19101, "name_ru"=>nil, "name_en"=>"Tonga")
RivalRegion.create("rivals_id"=>19201, "name_ru"=>nil, "name_en"=>"Dominica")
RivalRegion.create("rivals_id"=>19301, "name_ru"=>nil, "name_en"=>"Rothera")
RivalRegion.create("rivals_id"=>19302, "name_ru"=>nil, "name_en"=>"Troll")
RivalRegion.create("rivals_id"=>19303, "name_ru"=>nil, "name_en"=>"Showa")
RivalRegion.create("rivals_id"=>19304, "name_ru"=>nil, "name_en"=>"Mawson")
RivalRegion.create("rivals_id"=>19305, "name_ru"=>nil, "name_en"=>"Vostok")
RivalRegion.create("rivals_id"=>19306, "name_ru"=>nil, "name_en"=>"Casey")
RivalRegion.create("rivals_id"=>19307, "name_ru"=>nil, "name_en"=>"Dumont d Urville")
RivalRegion.create("rivals_id"=>19308, "name_ru"=>nil, "name_en"=>"South Pole")
RivalRegion.create("rivals_id"=>19309, "name_ru"=>nil, "name_en"=>"Palmer")
RivalRegion.create("rivals_id"=>19310, "name_ru"=>nil, "name_en"=>"GMT -6")
RivalRegion.create("rivals_id"=>19401, "name_ru"=>nil, "name_en"=>"Marshall Islands")
RivalRegion.create("rivals_id"=>100001, "name_ru"=>nil, "name_en"=>"Snowflake Island")
RivalRegion.create("rivals_id"=>200001, "name_ru"=>nil, "name_en"=>"Moon region 1")
RivalRegion.create("rivals_id"=>200002, "name_ru"=>nil, "name_en"=>"Moon region 2")
RivalRegion.create("rivals_id"=>200003, "name_ru"=>nil, "name_en"=>"Moon region 3")
RivalRegion.create("rivals_id"=>200004, "name_ru"=>nil, "name_en"=>"Moon region 4")
RivalRegion.create("rivals_id"=>200005, "name_ru"=>nil, "name_en"=>"Moon region 5")
RivalRegion.create("rivals_id"=>200006, "name_ru"=>nil, "name_en"=>"Moon region 6")
RivalRegion.create("rivals_id"=>200007, "name_ru"=>nil, "name_en"=>"Moon region 7")
RivalRegion.create("rivals_id"=>200008, "name_ru"=>nil, "name_en"=>"Moon region 8")
RivalRegion.create("rivals_id"=>200009, "name_ru"=>nil, "name_en"=>"Moon region 9")
RivalRegion.create("rivals_id"=>200010, "name_ru"=>nil, "name_en"=>"Moon region 10")
RivalRegion.create("rivals_id"=>200011, "name_ru"=>nil, "name_en"=>"Moon region 11")
RivalRegion.create("rivals_id"=>200012, "name_ru"=>nil, "name_en"=>"Moon region 12")
RivalRegion.create("rivals_id"=>200013, "name_ru"=>nil, "name_en"=>"Moon region 13")
RivalRegion.create("rivals_id"=>200014, "name_ru"=>nil, "name_en"=>"Moon region 14")
RivalRegion.create("rivals_id"=>200015, "name_ru"=>nil, "name_en"=>"Moon region 15")
RivalRegion.create("rivals_id"=>200016, "name_ru"=>nil, "name_en"=>"Moon region 16")
RivalRegion.create("rivals_id"=>200017, "name_ru"=>nil, "name_en"=>"Moon region 17")
RivalRegion.create("rivals_id"=>200018, "name_ru"=>nil, "name_en"=>"Moon region 18")
RivalRegion.create("rivals_id"=>200019, "name_ru"=>nil, "name_en"=>"Moon region 19")
RivalRegion.create("rivals_id"=>200020, "name_ru"=>nil, "name_en"=>"Moon region 20")
RivalRegion.create("rivals_id"=>200021, "name_ru"=>nil, "name_en"=>"Moon region 21")
RivalRegion.create("rivals_id"=>200022, "name_ru"=>nil, "name_en"=>"Moon region 22")
RivalRegion.create("rivals_id"=>200023, "name_ru"=>nil, "name_en"=>"Moon region 23")
RivalRegion.create("rivals_id"=>200024, "name_ru"=>nil, "name_en"=>"Moon region 24")
RivalRegion.create("rivals_id"=>200025, "name_ru"=>nil, "name_en"=>"Moon region 25")
RivalRegion.create("rivals_id"=>200026, "name_ru"=>nil, "name_en"=>"Moon region 26")
RivalRegion.create("rivals_id"=>200027, "name_ru"=>nil, "name_en"=>"Moon region 27")
RivalRegion.create("rivals_id"=>200028, "name_ru"=>nil, "name_en"=>"Moon region 28")
RivalRegion.create("rivals_id"=>200029, "name_ru"=>nil, "name_en"=>"Moon region 29")
RivalRegion.create("rivals_id"=>200030, "name_ru"=>nil, "name_en"=>"Moon region 30")
RivalRegion.create("rivals_id"=>200031, "name_ru"=>nil, "name_en"=>"Moon region 31")
RivalRegion.create("rivals_id"=>200032, "name_ru"=>nil, "name_en"=>"Moon region 32")
RivalRegion.create("rivals_id"=>200033, "name_ru"=>nil, "name_en"=>"Moon region 33")
RivalRegion.create("rivals_id"=>200034, "name_ru"=>nil, "name_en"=>"Moon region 34")
RivalRegion.create("rivals_id"=>200035, "name_ru"=>nil, "name_en"=>"Moon region 35")
RivalRegion.create("rivals_id"=>200036, "name_ru"=>nil, "name_en"=>"Moon region 36")
RivalRegion.create("rivals_id"=>200037, "name_ru"=>nil, "name_en"=>"Moon region 37")
RivalRegion.create("rivals_id"=>200038, "name_ru"=>nil, "name_en"=>"Moon region 38")
RivalRegion.create("rivals_id"=>200039, "name_ru"=>nil, "name_en"=>"Moon region 39")
RivalRegion.create("rivals_id"=>200040, "name_ru"=>nil, "name_en"=>"Moon region 40")
RivalRegion.create("rivals_id"=>200041, "name_ru"=>nil, "name_en"=>"Moon region 41")
RivalRegion.create("rivals_id"=>200042, "name_ru"=>nil, "name_en"=>"Moon region 42")
RivalRegion.create("rivals_id"=>200043, "name_ru"=>nil, "name_en"=>"Moon region 43")
RivalRegion.create("rivals_id"=>200044, "name_ru"=>nil, "name_en"=>"Moon region 44")
RivalRegion.create("rivals_id"=>200045, "name_ru"=>nil, "name_en"=>"Moon region 45")
RivalRegion.create("rivals_id"=>200046, "name_ru"=>nil, "name_en"=>"Moon region 46")
RivalRegion.create("rivals_id"=>200047, "name_ru"=>nil, "name_en"=>"Moon region 47")
RivalRegion.create("rivals_id"=>200048, "name_ru"=>nil, "name_en"=>"Moon region 48")
RivalRegion.create("rivals_id"=>200049, "name_ru"=>nil, "name_en"=>"Moon region 49")
RivalRegion.create("rivals_id"=>200050, "name_ru"=>nil, "name_en"=>"Moon region 50")
RivalRegion.create("rivals_id"=>200051, "name_ru"=>nil, "name_en"=>"Moon region 51")
RivalRegion.create("rivals_id"=>200052, "name_ru"=>nil, "name_en"=>"Moon region 52")
RivalRegion.create("rivals_id"=>200053, "name_ru"=>nil, "name_en"=>"Moon region 53")
RivalRegion.create("rivals_id"=>200054, "name_ru"=>nil, "name_en"=>"Moon region 54")
RivalRegion.create("rivals_id"=>200055, "name_ru"=>nil, "name_en"=>"Moon region 55")
RivalRegion.create("rivals_id"=>200056, "name_ru"=>nil, "name_en"=>"Moon region 56")
RivalRegion.create("rivals_id"=>200057, "name_ru"=>nil, "name_en"=>"Moon region 57")
RivalRegion.create("rivals_id"=>200058, "name_ru"=>nil, "name_en"=>"Moon region 58")
RivalRegion.create("rivals_id"=>200059, "name_ru"=>nil, "name_en"=>"Moon region 59")
RivalRegion.create("rivals_id"=>200060, "name_ru"=>nil, "name_en"=>"Moon region 60")
RivalRegion.create("rivals_id"=>200061, "name_ru"=>nil, "name_en"=>"Moon region 61")
RivalRegion.create("rivals_id"=>200062, "name_ru"=>nil, "name_en"=>"Moon region 62")
RivalRegion.create("rivals_id"=>200063, "name_ru"=>nil, "name_en"=>"Moon region 63")
RivalRegion.create("rivals_id"=>200064, "name_ru"=>nil, "name_en"=>"Moon region 64")
RivalRegion.create("rivals_id"=>200065, "name_ru"=>nil, "name_en"=>"Moon region 65")
RivalRegion.create("rivals_id"=>200066, "name_ru"=>nil, "name_en"=>"Moon region 66")
RivalRegion.create("rivals_id"=>200067, "name_ru"=>nil, "name_en"=>"Moon region 67")
RivalRegion.create("rivals_id"=>200068, "name_ru"=>nil, "name_en"=>"Moon region 68")
RivalRegion.create("rivals_id"=>200069, "name_ru"=>nil, "name_en"=>"Moon region 69")
RivalRegion.create("rivals_id"=>200070, "name_ru"=>nil, "name_en"=>"Moon region 70")
RivalRegion.create("rivals_id"=>200071, "name_ru"=>nil, "name_en"=>"Moon region 71")
RivalRegion.create("rivals_id"=>200072, "name_ru"=>nil, "name_en"=>"Moon region 72")
RivalResource.create("rivals_resource_id" => 3, "name" => "Oil")
RivalResource.create("rivals_resource_id" => 4, "name" => "Ore")
RivalResource.create("rivals_resource_id" => 11, "name" => "Uranium")
RivalResource.create("rivals_resource_id" => 15, "name" => "Diamonds")
RivalResource.create("rivals_resource_id" => 21, "name" => "Liquid Oxygen")
RivalResource.create("rivals_resource_id" => 24, "name" => "Helium-3")
RivalResource.create("rivals_resource_id" => 13, "name" => "Antirad")
RivalResource.create("rivals_resource_id" => 20, "name" => "Rockets")
RivalResource.create("rivals_resource_id" => 2, "name" => "Tanks")
RivalResource.create("rivals_resource_id" => 1, "name" => "Aircrafts")
RivalResource.create("rivals_resource_id" => 14, "name" => "Missiles")
RivalResource.create("rivals_resource_id" => 16, "name" => "Bombers")
RivalResource.create("rivals_resource_id" => 18, "name" => "Battleships")
RivalResource.create("rivals_resource_id" => 22, "name" => "Lunar Tanks")
RivalResource.create("rivals_resource_id" => 23, "name" => "Space Stations")
